Resources/Prototypes/Catalog/Fills/Lockers/heads.yml

Adds a fill for all head's of staff lockers to be cosmetic items without actual gear.
I intend to use it for the CentCom Arrivals map.
**Changelog**
No need.

Cosmetic Command Lockers

---

Content.Shared/Atmos/Miasma/PerishableComponent.cs

Oh boy, don't you love untested changes? I love untested changes.
closes #3 
This increases the rot timer to take longer overall, I'm looking for input as to how much longer it should be increased, as I'm going with five extra minuets for now. We could possibly bring it to twenty over all, but I don't know if that is quite justified.
**The rot consumes slower than before.**
Due to the increased round duration, I believe the time to rot should reflect that, with standard round times (1H 20M) it takes you about 12% of the round to rot, but with out extended round times (5 hours), that drops to 0.03. It should take more time for people to rot. I doubt there will be many times people actually rot due to antags, but I still think this should be increased not only because of antags, but the …

Increase Time To Rot (The Rot No Longer Consumes)

---

Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml

Adds an atmos and chemist arrival spawner.
Also reorganizes the whole thing to be alphabetical because it was driving me mad just looking at it.
I sucked at clearly defining what I wanted the first time.

More Arrivals Spawners

---

Content.Shared/CCVar/CCVars.cs

i made salvage expeditions give you 15 minutes and have a cooldown of 15 minutes
the old time was too short you couldn't RP also rounds are longer
i changed precisely 2 numbers in the config
**Changelog**
:cl:
- tweak: Salvage expeditions are now much longer but have a longer cooldown

salvage expeditions longer

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/clothing.yml

Refer to technical Details Section.
Seeing as when department heads leave, they likely aren't taking off their uniforms to go back to central command and enter cryosleep, there should be a way to easily make more, plus it gives HoP more to do. I made the decision to exclude Jackboots, Combat boots, and department head gloves. The gloves are namely to make any detectives have a bit of an easier time.
Adds the following clothing items to the Uniform Printer:
QM Hat, Flipped Hat, Cloak
Captain's Formal Suit, FOrmal Dress, Cloaks, Hard Hat, Cap Cap
HoP's Cap, Cloak
CE, CMO, RD, HoS Cloaks
HoS's Cowboy Hat, Formal Suit, Formal Dress, Parade Uniforms, Blue Suit, Grey Uniform
Engineering, CMO, RD, HoS Berrets

Add Department Head Clothing To Uniform Printer (Part 2 Electric Boogaloo)

---

Resources/Locale/en-US/station-events/events/vent-critters.ftl
Resources/Prototypes/GameRules/events.yml

- Gives all vent critter events an announcement, "Attention. A large influx of unknown life forms have been detected residing within the station's ventilation systems. Please be rid of these creatures before it begins to affect productivity."
- Makes vent critter events have a 10 second delay before spawning.
Should make the events less bullshit because now you've got a few seconds of warning to actually realize what's going on.
It's included for harmless ones too like roaches and mice so it shouldn't be able to get metagame'd either.

Vent Critter Alerts

---

Content.Client/Eye/Blinding/BlurryVisionOverlay.cs
Content.Shared/Eye/Blinding/Components/BlindableComponent.cs
Content.Shared/Eye/Blinding/Components/BlurryVisionComponent.cs

- Decreases the amount of damage needed to go perma blind, from 8 to 3.
- Makes the "blur" effect _way_ more present.
Stop fucking hurting you eyes.
- I can't remember the last time oculine was ever even used.
- Prevents people from doing engi's job a bit more.
- More punishing for being stupid.
https://github.com/cosmatic-drift-14/cosmatic-drift/assets/110078045/1b743441-77df-4bdb-9753-aa842b1b451d

Increase The Effect of Eye Damage

---

Resources/ServerInfo/Rules.txt

Changes I made which I'm not sure are correct, preferred, etc have a italicized question mark before and after them This looks like _?_
**Rule 2**
"...attempt to evade bans, ahelp questioning or..." has been changed to "...attempt to evade bans, ahelp questioning **,** or...", fixing the missing comma from the list.
**Rule 5**
"No sexual content, disgusting RP or gross statements." has been changed to "No sexual content, disgusting RP**,** or gross statements." fixing the missing comma from the list.
**Rule 7**
"...such as autoclickers, marcos, and such." has been changed to "...such as autoclickers, **macros**, and such." fixing the typo in marco.
**Rule 8**
_?_ "when it becomes over the top, uninteresting and the issue is repeated even after in-character punishment." has been changed to …

Fixes Minor Rules Typos

---

Resources/Prototypes/Roles/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Resources/Prototypes/Roles/Jobs/Civilian/bartender.yml
Resources/Prototypes/Roles/Jobs/Civilian/chef.yml
Resources/Prototypes/Roles/Jobs/Civilian/lawyer.yml
Resources/Prototypes/Roles/Jobs/Civilian/mime.yml
Resources/Prototypes/Roles/Jobs/Command/captain.yml
Resources/Prototypes/Roles/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/Roles/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Roles/Jobs/Medical/medical_intern.yml
Resources/Prototypes/Roles/Jobs/Medical/paramedic.yml
Resources/Prototypes/Roles/Jobs/Medical/senior_physician.yml
Resources/Prototypes/Roles/Jobs/Science/borg.yml
Resources/Prototypes/Roles/Jobs/Science/research_assistant.yml
Resources/Prototypes/Roles/Jobs/Science/research_director.yml
Resources/Prototypes/Roles/Jobs/Science/scientist.yml
Resources/Prototypes/Roles/Jobs/Science/senior_researcher.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml

- Makes Captain require 6 hours of total playtime.
- Makes all command roles require 4 hours of total playtime.
- Makes all security roles require 2 hours of total playtime.
- Removes the role timers on all other roles.
Admin discussion.

Role Timers For Command/Security

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/quickthreads.yml
Resources/Prototypes/_CD/Catalog/Fills/Boxes/general.yml

This adds all (current) versions of the pride pins into the quickthreads. These are in the form of two boxes, just to prevent adding nine new items to the vending machine.
Closes: [This Discord Thread](https://discord.com/channels/1163352113162768436/1181400509224063046/1181400509224063046) 
**Changelog**
Add: Pride Pins are now sold at the QuickThreads vendor in the terminal. There are two boxes containing one of each pride pin.

Pride Pins in Quickthread

---

Resources/Prototypes/Entities/Objects/Decoration/flora.yml

Make presents only safe.

---

Resources/Locale/en-US/_CD/reagents/RPmeds.ftl
Resources/Locale/en-US/_CD/reagents/meta/medicine.ftl
Resources/Prototypes/_CD/Reactions/medicine.yml
Resources/Prototypes/_CD/Reagents/medicine.yml

I decided to atomize RP meds because they ended up being more complicated than I thought.
This PR adds 3 painkillerss and a reagent that manages addictions. These reagents are primarily RP-based. Their main purpose is to act as meds that characters may need to take to deal with pain. They give RP prompts that you may or may not follow and have dangerous overdose effects. They all are detailed automatically in the Chemicals section of the guidebook, and can be found by searching for "Addict" or "Painkiller" when looking for chemicals that are addictive and chemicals that are painkillers, respectively. Their guidebook descriptions detail on how they work fairly well.
These chemicals are primarily for RP value and do not really provide any mechanical advantage whatsoever.
The rate at which …

Painkiller RP Meds + Addictine

---

Resources/Maps/_CD/ferrous.yml

Bar roundstart wiring has been fixed.
Science has been given two artifact containers roundstart.
Missing floortiles under doors in the service department have been fixed.
Kitchen has been given an alexander.
The blindspots in security's cells has been removed.
Library has been given a curadrobe and a book bag roundstart.
Library has been given a more dedicated area for their DND sessions.
Maints bar has received improvements.
Arrivals timers have been added in command and arrivals.
HoP line has received an improvement.
Medical now has a chemdrobe.
The bar closet space is now bar access instead of service.
Southern Maints has been given some wall lockers.
Science has been given more vents and scrubbers in some areas.
APCs have been renamed to be more identifiable on the power monitor.
Fax …

Ferrous V1.02

---

Resources/Prototypes/_CD/Entities/Structures/Storage/lockers.yml
Resources/ServerInfo/Guidebook/Cryosleep.xml

This adds two things, the cryosleep guidebook entry now includes a visualization for the Lost and Found Locker, along with the Lost and Found Locker directing to the cryosleep entry so its use is more clear.
Currently, unless you directly read the cryosleep entry or had seen the Lost and Found work during a round, it was unclear that it directly had a mechanic behind it.
**Changelog**
Tweak: The cryosleep guidebook entry has been lightly altered to be more clear of what the Lost and Found Locker looks like.

Lost & Found Locker Guidebook "Help"

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cigs.yml

Number of basic lighters has been increased to three, Flippo has been added in every shadysmokes. This adds up to 3 basic lighters and 2 Flippo's (Engraved Flippo was removed due to it being a thief objective)
I don't see any issues with letting people have more ease of access with wanting to smoke cigerettes, It's not like it's going to crash the server (Unless it fucking does)
**Changelog**
:cl:
- tweak: Two Flippo lighters have been added to ShadySmokes along with three basic lighters!

Adds Flippo's to the ShadySmokes

---

Content.Shared/CCVar/CCVars.cs

Changes the default round end time from 2 minutes to 5 to give more time to tie up RP ends.
Feels like a good number, enough time to settle down but not too long that it's obnoxious. I've done this manually several times here and on Upstream, people seem to like it.
Changes the default of the Cvar instead of using the Cvar because the Cvar was last known to crash servers at round end.
**Changelog**
The delay from when the round ends to when the game is returned to the lobby has been upped from 2 to 5 minutes.

Extend Round End Time

---

Content.Client/Traits/ParacusiaSystem.cs
Content.Server/Traits/Assorted/ParacusiaSystem.cs
Content.Server/_CD/Chemistry/ReagentEffects/ResetParacusia.cs
Content.Shared/Traits/Assorted/ParacusiaComponent.cs
Resources/Locale/en-US/_CD/reagents/RPmeds.ftl
Resources/Locale/en-US/_CD/reagents/guidebook.ftl
Resources/Locale/en-US/_CD/reagents/meta/medicine.ftl
Resources/Prototypes/_CD/Reactions/medicine.yml
Resources/Prototypes/_CD/Reagents/medicine.yml

We have been using various mixes of chemicals for an RP anti-psychotic for quite some time. This turns the most common mix we use into an actual chemical.  It also suppresses paracusia in almost the same way Diphenylmethylamine suppresses narcolepsy as I figured it was appropriate.
Should not really affect game balance in any way as it is an RP chem. Technically it is possible to put someone to sleep with it's overdose but chloral hydrate is a far more effective solution.
The name Saphrodipine was chosen mostly at random. I wanted to avoid using the name Haloperidol (what we have been using for this mixture IC) because it is apparently a real medication and I figure it is best to avoid such things.
The chem functions basically the same the other RP chems. To be able to suppress paracusia …

Anti-Psych RP Chem

---

Resources/Prototypes/GameRules/events.yml

Disables the terminator and clerical error events. (And probably doesn't fail tests.)
Terminator is a obvious since it's whole goal is to perma kill someone.
Clerical Error could be a up for a bit more debate, given it's nothing major but if I recall correctly we were leaning towards wanting to disable this one.

Disable Clerical and Terminator Events

---

Resources/Prototypes/Roles/Jobs/Security/senior_officer.yml

The senior officer role now spawns with sunglasses instead of security sunglasses.
Secglasses are meant to be a T2 research and have been removed from the roundstart kits of the rest of security. SO's got overlooked due to the nature of how we have been reverting their removal.
**Changelog**
tweak: Senior Officers now spawn with sunglasses instead of security sunglasses, this brings them in line with the rest of roundstart security.

Remove Senior Officers Roundstart Secglasses

---

Content.Shared/Preferences/HumanoidCharacterProfile.cs

Changed the limit on character descriptions from 512 to 1024 characters.
512 characters is not a very large amount, especially for an HRP server.
:cl:
- tweak: Character descriptions can now be up to 1024 chars in length

Larger Character Descriptions

---

Resources/Maps/_CD/ferrous.yml

I don't know why the diff is so big, here is the changelog:
AME Core is now in line with upstream's mapping standards.
More Generators have been added around the map for roundstart power.
The SWAT crate in security has been replaced with one that doesn't start with shotguns.
Disposals now will drop its contents correctly onto the belt instead of into the far wall.
Department Head Cosmetic Dressers have been mapped.
The outer armory windoor is now security access instead of armory access.
The inner bridge airlock is now glass.
Engineering has an engidrobe (Finally).
New Warp Points/Map Beacons have been added, I tried to convert over as many as I could, but I might have missed some.
A clown/mime room has been added above theater, its not a large space, but they can now fill out important …

Ferrous Update

---

Resources/Maps/_CD/ferrous.yml

Clown/Mime room is now theater access.
Atmos has been given another plasma tank, bringing their count to two.
The burn chamber for atmos is now both passive vents.
North Solars has been given some HV Cables to start with.
The TEG area has been expanded to allow for more breathability.
Perma now has some more games to play to pass the time if two prisoners are being held.
Most of these changes make atmos's life easier. Its no fun having 30 mins of the round without power. The alternative is we give more AME fuel/parts, which I'd rather not do. The TEG is significantly easier to set up now.
**Very Optional Changelog**
tweak: Ferrous has received yet another pass over, its version is now 1.04.

Ferrous Updates (V1.04 I think)

---

Resources/Prototypes/Maps/aspid.yml
Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/_CD/Maps/ferrous.yml

Adds the prisoner role to Box.
Standardizes map files we've changed.
Box is the only 40 pop map that properly supports a fun prisoner environment (it has a proper meeting room).
It was confusing to look at all the different styles so I just fixed that.

Box Prisoner Role + Map Prototype Touch Ups

---

Resources/Prototypes/_CD/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/_CD/Catalog/Fills/Lockers/security.yml

Replaces the security glasses in the HoS and Warden cosmetic lockers with sunglasses
To fit with Upstream balance.

Replace SecGlasses From Cosmetic Lockers

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/chefdrobe.yml
Resources/Prototypes/_CD/Catalog/VendingMachines/Inventories/quickthreads.yml

Adds all the Stylized Maid from #116 to the Quick Threads inventory, two of everything but the shoes which have three.
Adds just the half apron to the chef vend because I thought it fit enough in a kitchen setting (see the literal reason why half apron exists) and that someone might be able to get it to look nice.
I'm tired of people having to ahelp about it, and it should be obtainable in the first place.

Obtainable Stylized Maid Set

---

Content.Server/_CD/Roles/NotifyDepartmentSpecial.cs
Resources/Locale/en-US/_CD/job/job-description.ftl
Resources/Prototypes/_CD/Roles/Jobs/Wildcards/prisoner.yml

Implements https://github.com/cosmatic-drift-14/cosmatic-drift/issues/122
One possible issue is it looks like the prisoner is speaking over security radio, but this is applied before the shift assignment message so I doubt it would case too much confusion. I did this because the only entity that is readily available for JobSpecials is the character that is joining.
Add a new JobSpecial called NotifyDepartmentSpecial that notifies a radio channel with the given text upon the job joining. This is then added to the prisoner role.
**Changelog**
:cl:
- add (aquif): A notification is now played over security radio when a prisoner is assigned to the shift.

Add prisoner join notification for security radio

---

Resources/Prototypes/Entities/Objects/Specific/Service/vending_machine_restock.yml

Adds the Quick Threads to the wardrobe restock crate.
Should have some way to restock it. (Mostly because I like to keep it stocked as Central Command)

Make Quick Threads Restock-able

---

Resources/Prototypes/Entities/Objects/Fun/toys.yml

Removes the toy hammers power of gibbing someone
Prevents a supposedly harmless toy hammer from gibbing crewmates (it's an HRP environment, we don't need it)
Random gibbing from a literal hammer made of rubber can break immersion easily and only has uses as a shitter tool, I believe it has no place in CD
**Changelog**
:cl:
- tweak: Rubber hammers no longer have the possibility to gib

Remove the rubber hammers ability to gib people

---

Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/Roles/Jobs/Engineering/station_engineer.yml
Resources/Prototypes/Roles/Jobs/Engineering/technical_assistant.yml
Resources/Prototypes/Roles/Jobs/Medical/chemist.yml
Resources/Prototypes/Roles/Jobs/Science/borg.yml
Resources/Prototypes/_CD/Roles/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/_CD/Roles/Jobs/Medical/senior_physician.yml

Adds a two hour overall game time role timer for all engineering, chemistry (including SP), and borg jobs.
**Changelog**
All engineering jobs, chemistry, senior physician, and borgs, now have two hour overall role timers.

More Role Timers

---

Content.Server/StationEvents/Events/IonStormRule.cs
Content.Server/_CD/Traits/SynthComponent.cs
Content.Server/_CD/Traits/SynthSystem.cs
Content.Shared/Chat/TypingIndicator/TypingIndicatorComponent.cs
Resources/Locale/en-US/_CD/reagents/meta/biological.ftl
Resources/Locale/en-US/_CD/station/events.ftl
Resources/Locale/en-US/_CD/traits/traits.ftl
Resources/Prototypes/_CD/Reagents/biological.yml
Resources/Prototypes/_CD/Traits/traits.yml

had to fuck with upstream code for this but *surely* it's fine.
Currently:
gives synth blood instead of whatever blood you had before
changes typing indicator to robor
30% chance of being alerted of an ion storm when one happens

Synth Trait

---

Resources/Prototypes/Species/arachnid.yml
Resources/Prototypes/Species/diona.yml
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/Species/reptilian.yml

All species have an updated marking limit to accommodate for markings that can be used in synergy to create more unique and personalized characters. Different types of markings (ie skin markings vs. gauze) have been taken into account as well. 
My lizzer was prevented from having both wings and underbelly, so I decided to take a look at every species. Since this is HRP and whitelist only, I believe we can give more trust to our players not to abuse it to create some horrendous monster.
- Chest now has 3 points (previously 1): Several chest markings can make a nice synergy with one another.
- Arms & Legs now have 6 points each (previously 2): Allows use of skin markings and gauze for each leg.
Example Arachnid:
- Head now has 3 points (previously 2) : Better synergy.
- Head (Top) now has 2 …

Updates all species' marking limits to be more lenient.

---

Resources/map_attributions.txt

Things were hidden and I didn't realize the file existed, it now includes Ferrous in the list under a new category. Rest of the PR template has been deleted because this doesn't change anything else.

Update Map Attributions To Include Ferrous

---

Content.Client/Preferences/UI/HumanoidProfileEditor.xaml
Content.Client/Preferences/UI/HumanoidProfileEditor.xaml.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs
Resources/Locale/en-US/preferences/ui/humanoid-profile-editor.ftl

Makes the height box into a slider
The previous UI listed the height multiple times and had the reset button in a weird spot, in the process of fixing that I decided to turn it into a slider.
Because the max/min height depends on the prototype, we need to lerp between them so the slider ranges between 0.0 and 1.0. 
**Changelog**
:cl: Aquif
- tweak: The height box is now a slider

Make the height textbox into a slider.

---

Content.Server/Connection/ConnectionManager.cs

Makes it so whitelist doesn't need to be checked for all connected players every time someone wants to join
Instead of checking the whitelist of everyone whenever someone joins, only checking a single player who has fully connected and storing the result is much better for performance
This just checks a players whitelist status when they've connected, and if they're whitelisted, store them. They'll be removed again whenever they leave.
~~Do note that my implementation assumes the whitelist status never changes. If it is disabled while there are people on the list, it wont be properly reset.~~ Fixed in 48daeb7

Improve whitelist check

---

Content.Shared/CCVar/CCVars.cs

Changes the cvar default to 20 instead of 10.
To make the database cry. And also because it could be nice for players who have an excess of characters, shouldn't be used by the majority of people though.

20 Character Slots

---

Resources/Prototypes/_CD/Catalog/Fills/Backpacks/StarterGear/startergear.yml

This PR adds the Log Probe Cartridge to the private investigators starting gear.
**Changelog**
Simyon: Private investigators now start with a log probe cartridge

Add log probe to private investigator starting gear

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs

Title
It was annoying me that it did not clear the search bar upon pressing reset. Also, this is a desync technically because the search field is cleared server side.
**Changelog**
Not required

Make records console reset button clear search bar

---

Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml

The arrivals spawner was the correct icon, but the standard spawner was not. This makes both the same icon, the detective's icon. I might go through again and create a new icon for the PI specifically later, but for now this is good. (I did test this ingame, I just forgot to grab media, sorry. I can grab media if asked.)

Update Standard PI Spawn To Correct Icon

---

Content.Server/Item/ItemSystem.cs
Content.Shared/Item/SharedItemSystem.cs

Fixes a desync upon inserting a stack into a container that already had a stack of the same item type. 
UpdateUI was only being called server side which has no body. We move the call to Shared so it also gets called on the client.
I don't think media is needed, but I could record before and after videos upon request.
**Changelog**
:cl: Aquif
- fix: Inserting stackables into an inventory that already contained items of the same type updates the inventory viewer

Fix list inv desync upon inserting stackables

---

Content.Server/_CD/Roles/NotifyDepartmentSpecial.cs

I fixed the prisoner announcement.
Previously the person "saying" the announcement was the prisoner which was on the arrivals terminal. This caused the message to only be relayed to people on the arrivals terminal. Now we use the station grid. This has the side-effect of people on the arrivals terminal not being notified, but I don't think this is a big deal.
**Changelog**
:cl:
- fix: The prisoner announcement actually works now

Fix prisoner announcement

---

Resources/Prototypes/_CD/Catalog/VendingMachines/Inventories/quickthreads.yml

i did in it quickthreads to prevent conflicts with namespace or something.
why did i do it? well you see it is because someone wanted them.
there are now 2

add sunglasses to quickthreads

---

Resources/Prototypes/Maps/aspid.yml
Resources/Prototypes/Maps/atlas.yml
Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/Maps/cluster.yml
Resources/Prototypes/Maps/core.yml
Resources/Prototypes/Maps/fland.yml
Resources/Prototypes/Maps/gemini.yml
Resources/Prototypes/Maps/marathon.yml
Resources/Prototypes/Maps/meta.yml
Resources/Prototypes/Maps/omega.yml
Resources/Prototypes/Maps/origin.yml
Resources/Prototypes/Maps/packed.yml
Resources/Prototypes/Maps/reach.yml
Resources/Prototypes/Maps/saltern.yml
Resources/Prototypes/_CD/Maps/ferrous.yml

Redoes all the map vote populations.
Should be something like this:
Fland: (Unused)
Gemini: 45+
Origin: 45+
Box: 35+
Meta: 35+
Bagel: 25 - 55
Marathon: 25 - 55
Aspid: 25 - 45
Core: 25 - 35
Ferrous: 15 - 35
Cluster: 5 - 25
Omega: 5 - 25
Packed: 5 - 25
Atlas: 0 - 15
Saltern: 0 - 15
Reach: 0 - 5
To make it so admins don't have to constantly run custom votes.
The numbers are slightly arbitrarily picked, but based off of my original list I was doing for map votes. We can play it by touch from here on out doing adjustments when we need.

New Map Pops

---

Content.Server/_CD/Roles/NotifyDepartmentSpecial.cs

Make the prisoner notification only notify for the largest grid and arrivals.
Ghosts are able to hear it twice, but non-ghosts should only hear it once.

Prisoner join should not spam radio anymore

---

Resources/Prototypes/_CD/Roles/Jobs/Security/senior_officer.yml

Role maintenence - Senior officers now roundstart with secglasses like the rest of the roles. Secglasses are now round start and SO just needed to be updated to match.
No CL
Its untested, so if something is broken let me know and I'll fix it.

Give the senior officers back their secglasses

---

Resources/Locale/en-US/_CD/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/Jobs/Medical/medical_doctor.yml
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Civilian/private_investigator.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Medical/senior_physician.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Science/senior_researcher.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Security/senior_officer.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Wildcards/prisoner.yml
Resources/Prototypes/_CD/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/role_loadouts.yml
Resources/Prototypes/_CD/Roles/Jobs/Civilian/private_investigator.yml
Resources/Prototypes/_CD/Roles/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/_CD/Roles/Jobs/Medical/senior_physician.yml
Resources/Prototypes/_CD/Roles/Jobs/Science/senior_researcher.yml
Resources/Prototypes/_CD/Roles/Jobs/Security/senior_officer.yml
Resources/Prototypes/_CD/Roles/Jobs/Wildcards/prisoner.yml

Patches all the senior, PI, and prisoner roles to have loadouts. (Primarily just their jumpsuit choice due to that being rolled into loadouts.)
Normal medical doctors don't get access to the physician beret anymore.
I also gave PI a grab bag of items that seemed to fit their theme in their loadout, but apart from that touched basically nothing else.
Mostly just because not being able to pick between bags or jumpsuit/skirt choice sucks.
**Changelog**
CD roles (seniors, private investigator, and prisoner) now have loadouts.

CD Loadouts Patch

---

Resources/Prototypes/Entities/Objects/Specific/Janitorial/trashbag.yml

Jank mobile webedit
To allow people to put it on belts and generally carry it around easier. Not that worried about trash arbitrage.

change trash bag storage

---

Resources/Prototypes/Entities/Structures/Power/smes.yml

Jank mobile webedit 2
Necessary for our arrivals system to prevent power from running out roundstart. Also better to prevent constant blackouts.

Double SMES capacity 

---

Resources/Prototypes/Entities/Mobs/Species/slime.yml

Jank Webedit 3
Slime storage is significantly bigger than I thought upstream, this should bring it more inline with that.

Increase Slime Storage

---

Resources/Prototypes/Maps/atlas.yml
Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/Maps/cluster.yml
Resources/Prototypes/Maps/core.yml
Resources/Prototypes/Maps/marathon.yml
Resources/Prototypes/Maps/meta.yml
Resources/Prototypes/Maps/oasis.yml
Resources/Prototypes/Maps/omega.yml
Resources/Prototypes/Maps/origin.yml
Resources/Prototypes/Maps/packed.yml
Resources/Prototypes/Maps/reach.yml
Resources/Prototypes/Maps/saltern.yml

Changes Oasis to 35 minimum players, akin to Meta and Box.
Fixes Reach, Packed, and Marathon prototypes that were edited by an Upstream merge.
Labels all map prototype changes with CD markers.
Oasis looks about Box sized.
The rest are just fixes.

Map Pop Fixes

---

Resources/Locale/en-US/_CD/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Security/security_officer.yml
Resources/Prototypes/_CD/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/role_loadouts.yml

Add the ability for security to chose between sechuds and sec glasses in the loadout editor.
It was annoying me this was not the case.
**Changelog**
:cl: Aquif
- add: Security can now select sechuds via loadouts.

Add loadout for security glasses vs hud

---

Content.Server/_CD/Records/CharacterRecordsSystem.cs
Content.Shared/Preferences/HumanoidCharacterProfile.cs

Add some additional logging statements to the event handler that initializes records.
Somehow, profiles get passed to the character records system that don't have records. I think that after this PR all possibilities for this case have been closed. The commit message for 1aca376bbfd2685cf7eeadeea154d142f3850e16 has more info.
:cl: Aquif
- fix: Hopefully fix the issue causing character records to not show up in game for some characters. Please let aquif know if the issue still persists.

Hopefully mix the missing records issue.

---

Resources/Prototypes/Roles/Jobs/Security/detective.yml
Resources/Prototypes/Roles/Jobs/Security/head_of_security.yml
Resources/Prototypes/Roles/Jobs/Security/security_officer.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml

Fix the issue reported by Nairod where the loadout editor's visualization would not properly update for the security glasses choice.

Remove secglasses from gear in favor of loadouts

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/skeleton.yml

Replaces closet skeleton rules to imply they are covered by self-antag rules.
**Changelog**
We usually don't do rule change alerts, but I believe this one is substantial enough to warrant. Skeletons are now held to the same antag standards as any crew, meaning they should ahelp for permission before committing crimes.

Skeleton Rules

---

Resources/Prototypes/Roles/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/Roles/Jobs/Security/detective.yml

Fixes Atmos and Detective roletimers being departmental hours instead of overall gametime.
Fixes.

Roletimer Fixes

---

Resources/Prototypes/_CD/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/_CD/Voice/speech_emotes.yml

Title. The vulp emote wheel is still a bit too crowded. However, I will leave
that for someone else to fix.
**Changelog**
:cl: Aquif
- fix: Vulpkin emotes can no longer be used by non-Vulpkin.

Whitelist vulp emotes to vulpkin

---

Resources/Prototypes/Entities/Objects/Specific/Salvage/ore_bag.yml

Ore bags can fit four stacks of ore now.
It's a webedit, but it should work, right? :clueless:
Salvaging with the previous ore bag capacity was kind of painful - 175 was only enough room for slightly under three stacks. Now it should be less painful.
This changes two numbers - it sets the capacity to 240, and the size to 241, in line with the old capacity and size (175 and 176 respectively).
Shouldn't break anything, I'd hope.
**Changelog**
:cl:
- tweak: Ore bags can now fit considerably more ore.

Increase ore bag capacity

---

Resources/Prototypes/Maps/oasis.yml

Adds Senior Roles to Oasis.
And also adjusts the security roles;
- Security Officer: 8 -> 3
- Cadet: 4 -> 2
- Lawyer: 3 -> 2
Updating to match CD standards.

Adjusted Oasis Roles

---

Resources/Prototypes/GameRules/unknown_shuttles.yml

Disables the clown shuttle.
Changes the syndicate evac shuttle to weight 1 from weight 2.
Clowns are insanely chaotic.
Syndicate forces can be stressful for security, but still good for RP as they're not geared to kill.

Adjust Unknown Shuttle Events

---

Resources/Prototypes/GameRules/events.yml

Lowers the weight and the chance that Revenants will spawn and increases the minimum time.
As discussed in discord they show up a bit too frequently and often dominate a
round. This makes them rarer and because they can only show up later in the
round they will be less of an issue if they show up.
**Changelog**
:cl: Aquif
- tweak: Revenants should spawn less frequently.

Nerf chance of reveanant

---

Resources/ServerInfo/Rules.txt

- Splits the "dick be a dick" rule in half, now having a separate rule for crime rules.
- Adds a section about not being allowed to kill yourself while in security custody without ahelping.
- Introduces a small rule of thumb going over what we consider a minor crime opposed to a major crime.
- Clarifies that the Arrivals Shuttle and end of round Central Command station are not places to commit crime.
---
- Adds a new, "don't crowd RP situations" rule designed to protect things like security and medical from being swamped with people barging into their work.
---
**Changelog**
_[This is either a progress report done by you, or announcement done by me, you decide Lank.]_
Security have gotten a few Quality of Life changes in the form of rules. 
If you'd like to read in full, …

Security QoL Rules

---

Resources/Prototypes/Catalog/Fills/Items/firstaidkits.yml

Medkits are currently missing pills. This fixes the issue and bring them inline
with the balance upstream. The only thing that is a bit weird is that the pill
canisters are not full. This is also the case upstream, so I don't think it is
a bit deal
Obvious bug
```sh
cp /home/$USER/src/wizden/Resources/Prototypes/Entities/Specific/Medical/healing.yml .
```
**Changelog**
:cl:
- fix: Medkits are no longer lacking pills

Sync medkits with upstream

---

Resources/Prototypes/Atmospherics/gases.yml

This is an experimental change to hopefully make cargo have less money. It
would also provide more reason for atmos to optimize frezon setups. Trit was
also nerfed because if it was not, it would have sold for more than frezon.
See the [discussion on discord](https://discord.com/channels/1163352113162768436/1163713936231764059/1245234514318589953)
TLDR: Atmos can produce enough cash for cargo to buy luxury hardsuits for the
entire station in around 4 hours.
**Changelog**
:cl: Aquif, Ridiue
- tweak: Selling freezon and tritium got massively nerfed. This is an experimental change and will be reverted if it does not improve gameplay.

Nerf frezon and trit prices.

---

Resources/Prototypes/Entities/Objects/Fun/Instruments/instruments_wind.yml

Changes the size of recorders from 24 to 5.
I am a recorder player. It does not take *24 bag storage* to fit this stupid fucking instrument in your bag.
**Changelog**
:cl: rain
- fix: Fixed an evil curse with recorders causing them to become the least portable instrument ever

Make recorders portable

---

Content.Shared/Clothing/Components/SkatesComponent.cs
Content.Shared/Damage/Systems/DamageOnHighSpeedImpactSystem.cs

This PR visually and statistically improves how Skates work.
I didn't like how they worked.
This lowers the speed damage by 0.05. This also modifies one line of upstream code, to use `TryParalyze` instead of `TryStun`. This was changed so that wearers of the skates would actually fall, and not just stand in the middle of the hallway like an idiot if they accidentally bumped into a table or an airlock.
**Changelog**
:cl:
- fix: Fixed fun!

Rollerskate improvements

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/janidrobe.yml

This adds 2 pairs of galoshes to the JaniDrobe
This is so that when the janitor slots are filled and the HOP hires another janitor or two, they can get boots so they don't have to worry about slipping on puddles.
**Changelog**
:cl:
- tweak: Added 2 galoshes to JaniDrobe

Add galoshes to JaniDrobe

---

Resources/Prototypes/Entities/Objects/Misc/machine_parts.yml
Resources/Prototypes/Entities/Objects/Tools/fulton.yml
Resources/Prototypes/Stacks/Materials/Sheets/glass.yml
Resources/Prototypes/Stacks/Materials/Sheets/metal.yml
Resources/Prototypes/Stacks/Materials/Sheets/other.yml
Resources/Prototypes/Stacks/Materials/crystals.yml
Resources/Prototypes/Stacks/Materials/ingots.yml
Resources/Prototypes/Stacks/Materials/materials.yml
Resources/Prototypes/Stacks/Materials/ore.yml
Resources/Prototypes/Stacks/Materials/parts.yml
Resources/Prototypes/Stacks/consumable_stacks.yml
Resources/Prototypes/Stacks/engineering_stacks.yml
Resources/Prototypes/Stacks/floor_tile_stacks.yml
Resources/Prototypes/Stacks/medical_stacks.yml
Resources/Prototypes/Stacks/power_stacks.yml
Resources/Prototypes/Stacks/science_stacks.yml

When we re-added item sizes during the upstream merge we forgot to also revert
the part of 09256cfaa572d326840edaea1dc0268cd9def5e3 that removed item sizes from the YAML.

Partially revert "Makes machine parts stackable, removes unused field in stack prototypes (#28434)"

---

Content.Shared/CCVar/CCVars.cs

Should happen about, on average, 2.4x less frequently. This is to account for our slower, and longer, rounds.

Lower Meteor Frequency

---

Content.Server/Shuttles/Systems/ArrivalsSystem.cs

This is to, hopefully, fix arrivals being paused. Entirely untested, but that's why we're a playtest baby.

Revert part of 'Make station components use StationPostInitEvent' 

---

Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs

Now arrivals spawns will unpause the map they're on when used. This way people won't spawn on paused maps.

Hopefully Fix Arrivals Pausing

---

Resources/Prototypes/Roles/Jobs/Cargo/salvage_specialist.yml
Resources/Prototypes/Roles/Jobs/Security/warden.yml
Resources/Prototypes/_CD/Roles/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/_CD/Roles/Jobs/Medical/senior_physician.yml
Resources/Prototypes/_CD/Roles/Jobs/Science/senior_researcher.yml
Resources/Prototypes/_CD/Roles/Jobs/Security/senior_officer.yml

Adds a two hour overall role timer to salvage.
Adds a three hour overall role timer to all senior roles and warden.
Salvage is for grief protection.
Warden and senior roles are kind of arbitrary but it felt right because they can be treated as 2ICs, as well as the fact that only one slot exists for each of them so ensuring griefers don't get those spots is good.
**Changelog**
Salvage now has a two hour game time role timer.
Warden and all senior roles now have a three hour game time role timer.

Salvage and Senior role timers

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_CD/Recipes/Lathes/electronics.yml

Gives the circuit imprinter recipes to create all three record computers without research or anything.
In case a map is missing one or one got destroyed.
**Changelog**
Record computer boards can now be made in the circuit imprinter.

Lathe-able Record Boards

---

Content.Shared/Chat/TypingIndicator/TypingIndicatorComponent.cs

AutoGenerateComponentState got overwritten during the upstream merge. It's now readded.

Fix Synth Typing Indicator

---

Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
Resources/Prototypes/_CD/Loadouts/role_loadouts.yml
Resources/Prototypes/_CD/Roles/Jobs/Civilian/private_investigator.yml
Resources/Prototypes/_CD/Roles/Jobs/Engineering/senior_engineer.yml
Resources/Prototypes/_CD/Roles/Jobs/Medical/senior_physician.yml
Resources/Prototypes/_CD/Roles/Jobs/Science/senior_researcher.yml
Resources/Prototypes/_CD/Roles/Jobs/Security/senior_officer.yml

- Avalis and Vulp now spawn with survival boxes.
- All CD unique roles now spawn with species matching survival boxes (excluding prisoner for the boxes point) and survival gear.
Maintenance.
**Changelog**
Survival gear has been fixed so all CD unique roles and species get their appropriate survival equipment and boxes.

Fix Survival Gear For CD Roles

---

Content.Server/Mind/Commands/RenameCommand.cs
Content.Server/_CD/Records/CharacterRecordsSystem.cs

Currently if a player joins with a stupid name and is not erased banned for
some reason there is no way for admins to remove the name from records.
Also added records support to the rename command.

Make character name reset upon resetting records.

---

Resources/Maps/_CD/ferrous.yml

Contraband Storage Crate in the armory, Disposals Windoor to prevent spacing, disposals pipe properly drops on the conveyor now. RD's office now has the robot control console, Emergency nitrogen tanks have been mapped in maints and other areas (Remember you can ask cargo and atmos for more), The perma visitation windoors now close eachother.
Ferrous lacked a few details that bugged me. Along with missing a robotics control console and nitrogen emergency closets for vox and slimes.
Vox Box
Second Asteroid Bolted to the South East of the station
CourtRoom
Event Shuttle Docking Port
PI Office (Run down and will need repaired)
**Changelog**
(You are free to shorten or link to the PR as much as you like)
Ferrous update: Contraband Storage Crate in the armory, Disposals Windoor to prevent …

Ferrous Update (1.09)

---

Content.Shared/CCVar/CCVars.cs

Reverts cosmatic-drift-14/cosmatic-drift#114
I asked in axolotl's dev chat a long time ago how they extend the round end and YuNii said they just change this CVAR. It must have been broken when we tried to change it. The only difference is Axolotl changes it in the config instead of the repo. If this does not work I don't know what to say.

Revert "Revert "Extend Round End Time""

---

Content.Shared/CCVar/CCVars.cs

Disables showing the admin rank in the ahelp window per admin consensus.

Disable admin rank in ahelp window

---

Content.Client/Lobby/UI/HumanoidProfileEditor.xaml
Resources/Locale/en-US/_CD/job/department.ftl
Resources/Locale/en-US/_CD/job/editor-warnings.ftl
Resources/Locale/en-US/job/department-desc.ftl
Resources/Locale/en-US/job/department.ftl
Resources/Prototypes/Roles/Jobs/departments.yml
Resources/Prototypes/_CD/Roles/Jobs/departments.yml

- **Recategorize jobs to fit their use on CD**
- **Warning about job rule for HumanoidProfileEditor**
This is just a ""temporary"" measure until somebody enforces this mechanically. See #347 
**Changelog**
:cl:
- add: Reorganize the character editor to make it clear what jobs are in what department for the "two department + service" rule

Reorganize roles and add warning about the two job rule

---

Resources/Locale/en-US/_CD/job/department.ftl
Resources/Prototypes/_CD/Roles/Jobs/departments.yml

Fixes the Yaml linter issue on the latest commit. This issue was introduced by
the upstream merge adding a new required field to one of the prototypes I used
causing the tests to pass on that branch (but fail after merge) because
upstream was not merged on the branch.

Fix missing locale issue cause by upstream merge

---

Resources/Locale/en-US/datasets/figurines.ftl
Resources/Prototypes/Datasets/figurines.yml

Redoes a majority of the new figurine lines to fit the CD environment and add a couple inside jokes.
A lot of the original ones just didn't suit CD.
(I did not mark every single difference, instead just labeling the top of the file with "Heavily edited by CD." I can adjust this if Lank or Aquif would like.)
**Changelog**
Most figurines have had their voice lines changed or had lines added.

Redo Figurine Lines

---

Content.Server/StationEvents/Components/BasicStationEventSchedulerComponent.cs
Content.Server/StationEvents/Components/RampingStationEventSchedulerComponent.cs
Resources/Prototypes/GameRules/meteorswarms.yml
Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/game_presets.yml

I'm not 100% sure how exactly this works, but I *believe* this should result in less events spawning, more similar to how it was before the refactor.

(hopefully) make the event scheduler less chaotic

---

Resources/CDMapPatches/box.yml
Resources/CDMapPatches/cog.yml
Resources/CDMapPatches/oasis.yml
Resources/CDMapPatches/omega.yml
Resources/CDMapPatches/packed.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/Maps/cog.yml
Resources/Prototypes/Maps/oasis.yml
Resources/Prototypes/Maps/omega.yml
Resources/Prototypes/Maps/packed.yml

Adds a map patch for the rest of the remaining non-CD maps that didn't have one. (Excludes Reach, because Reach, don't think I need to explain that one.)
##
**Box**
- Adds a LnF locker in the command conference room above HoP.
**Cog**
- Adds a LnF locker in HoP's bedroom.
**Oasis**
- Adds a LnF locker in the command conference room.
- Adds an employment records computer in every Head room excluding HoP and RD. (Space issues.)
**Omega**
- Adds a LnF locker in the bridge.
- Adds a an employment records computer in the bridge.
- Adds a medical records computer by the surgery room.
**Packed**
- Adds a LnF locker in the bridge.
Lost and Found lackage.
**Changelog**
Every map should have a Lost and Found locker now, plus records computers where relevant.

More Map Patches

---

Resources/Prototypes/Loadouts/Jobs/Cargo/quartermaster.yml
Resources/Prototypes/Loadouts/Jobs/Command/captain.yml
Resources/Prototypes/Loadouts/Jobs/Command/head_of_personnel.yml
Resources/Prototypes/Loadouts/Jobs/Engineering/chief_engineer.yml
Resources/Prototypes/Loadouts/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Loadouts/Jobs/Science/research_director.yml
Resources/Prototypes/Loadouts/Jobs/Security/head_of_security.yml

Removes the time-gate on all head mantles.
Doesn't fit with our style, you could get them on the Terminal round-start anyways.
**Changelog**
Mantles are no longer time locked in loadouts.

Remove Mantle Timers

---

Resources/Locale/en-US/_CD/station/events.ftl
Resources/Prototypes/GameRules/meteorswarms.yml

Meteor swarms and space dust now give custom announcements based on the severity, so crew and engineering can hamper their expectations accordingly.

Add custom meteor swarm announcements 

---

Resources/Prototypes/Entities/Clothing/Shoes/boots.yml
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml

Removes the slowdown buff from jackboots and gives them to combat boots instead.
Gives all security roles combat boots instead of jackboots.
Redoes the description of jackboots since it was outdated.
Before jackboots were considered the security version and combat boots were considered vanity.
Problem; our players enjoy drip, jackboots are a pretty popular choice. They're also already in the QuickThreads vendor and maints loot.
Solution; make combat boots the security version and make jackboots vanity. It just makes more logical sense name wise, and we don't have syndicates/nukies to worry about anyways. (Easy enough to handle by just giving them jackboots too.)
**Changelog**
Jackboots had their slowdown reduction removed, and in their place combat boots now have it. Security now also all …

Move Slowdown Buff to Combat Boots

---

Resources/Prototypes/Entities/Objects/Materials/ore.yml
Resources/Prototypes/Stacks/Materials/ore.yml

Ore bags currently have an issue where they do not fill to capacity and are significantly smaller than their upstream counterpart to a crippling level. This should hopefully fix the issue when mining materials where the ore bag fills too quickly and as well as not to capacity.
Salvagers currently cannot mine as much ore as they probably should be able to vs upstream, meaning it takes more trips and therefore more time to mine due to having to go back and empty out the ore bags very frequently.
N/A
**Changelog**
:cl:
- tweak: Ore is now smaller!

Reduce listinv ore size

---

Resources/ServerInfo/Guidebook/_CD/Mobs/Avali.xml

When I made the guidebook I added a pretty severe typo for the temperatures. This fixes it. Their actual temperature range is -50C to 36C. Not -35C.
Correct information in guidebooks are important.
XML text change.
(Note, I haven't tested in game. If I need to I can, just ask, but this should be fine.)

Avali Guidebook Temp Typo Fix

---

Content.Server/RoundEnd/RoundEndSystem.cs
Content.Server/_CD/RoundEnd/ShuttleVoteSystem.cs
Content.Shared/CCVar/CCVars.cs

Fixed shuttle votes not using game time and the extremely cursed way we prevented people from recalling the shuttle.

Make shuttle votes use game time

---

Resources/Prototypes/Entities/Markers/Spawners/Random/anomaly.yml

These are fairly dangerous and I've heard from others upstream that they appear far too frequently for even LRP. With how many anomalies are often generated in rounds 1/20 should be more appropriate than 1/3 (assuming this works the way I think it does).

significantly nerf anomalous infection chance

---

Resources/Prototypes/Roles/Jobs/Fun/visitors_startinggear.yml

- Removes all PDAs from the unknown shuttle ghost roles.
- Changes all unknown shuttle ghost roles to have long range headsets (hailing) instead of departmental ones.
- The fact they were already labeled as visitor is kind of strange, and also has like several issues according to SOP where the whole gist is the Captain is the one granting them visitor-ship. (Honestly a replacement for these should probably be added, but I can't be fucked, it's past midnight.)
- Headsets because we added them for a reason in like the original PR- yeah.

Remove PDAs and Headsets from Shuttle Roles

---

Resources/Prototypes/_CD/Entities/Objects/Misc/paper.yml

As reported by players, the Ledger is impractically large, so this halves the size and makes it fit in jackets
It was bigger then a full oxygen tank
Changes _CD's paper.yml, changes a 20 to a 10
**Changelog**
* Tweak: Halved the size of the detective ledger

Detective Ledger adjustment

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/human_hair.yml

Sector Umbra backport.
https://github.com/Sector-Umbra/Sector-Umbra/pull/141
Not tested in-game but probably fine.
CL: Vulpkin can now use human hair styles. (Credit to SharkskyRaeJepsen)
I don't think they are in the CD discord.

Add human hair to vulps

---

Resources/Prototypes/_CD/Entities/Mobs/Species/avali.yml

Title / Copied speech tag added to Avali in RMC.
Speech sounds were broken, this fixes it.
3 lines of code in avali species yml
**Changelog**
:cl:
fix: Avali now chirp and squeak correctly.

Avali Speech Fix.

---

Resources/Prototypes/_CD/Loadouts/Jobs/Medical/paramedic.yml

The EMT Jacket properly spawn and no longer means players spawn without a jumpsuit.
Bug - Closes #455

Fix EMT Jacket

---

Content.IntegrationTests/Tests/Commands/SuicideCommandTests.cs
Content.Shared/Atmos/Atmospherics.cs

Reverts commit 37fffca6155b1b02398baca38677f17a7abddbfe.
The major argument for reducing the damage in https://github.com/space-wizards/space-station-14/pull/29478 boils down to "what if the shuttle gets bombed". This is a non-issue on CD given that ideally the shuttle should never be bombed without a very good reason.
In my opinion spacing *should* be a punishing and unfair mechanic. If you are going out into space without a spacesuit you are doing something that should be highly mechanically discouraged. Given that nature of CD being a RP server it is fairly immersion breaking to see John Paramedic going out into space to recover the body. If you blow a hole in the wall of the space station it *should* be a catastrophic event with little counterplay; I think the drama from that would …

[RFC] Revert low pressure damage

---

Content.Shared/Examine/ExamineSystemShared.cs

Makes it so you can view character descriptions from 8 tiles away instead of 3.
I remember RMC doing this and in general, I don't want to have to hug someone to read their typically at least one paragraph long description.
**Changelog**
You can now view character descriptions from a much greater range.

Increase Character Description Examine Range

---

Content.Shared/Atmos/Rotting/PerishableComponent.cs
Resources/Prototypes/Entities/Objects/Specific/Medical/morgue.yml
Resources/Prototypes/Procedural/salvage_rewards.yml
Resources/Prototypes/Reagents/medicine.yml
Resources/Prototypes/Recipes/Reactions/medicine.yml
Resources/ServerInfo/Guidebook/Medical/Cryogenics.xml
Resources/ServerInfo/Guidebook/Service/Botany.xml

These frankly make rotting slowly something that medical can just completely bypass. With the timer increased it should be rare enough as-is, and I think those deaths should remain impactful rather than being a minor inconvenience. 
Also edited to remove necrosol because while perma-killing by poison is a very uncommon strat, I think it's better to leave it as an option for antags and the like, especially in a situation like this where the "rare" chems are basically just an inconvenience.

Remove Opporozidone and Cloning, Increase Rot Timer

---

Content.Server/Connection/ConnectionManager.Whitelist.cs

title
the return was the wrong way around
the connecting player (data.UserId) isn't in the connected players list yet, so theres no need to check their status

fix non-whitelisted slots not working 

---

Content.Shared/_CD/Clothing/ClothingBlockSlotsOnEquipComponent.cs
Content.Shared/_CD/Clothing/ClothingBlockSlotsOnEquipSystem.cs
Resources/Locale/en-US/_CD/clothing/clothing-slots.ftl
Resources/Locale/en-US/_CD/clothing/components/clothing-block-slots-on-equip-component.ftl
Resources/Prototypes/_CD/Catalog/Fills/Items/belt.yml
Resources/Prototypes/_CD/Entities/Clothing/Belt/belts.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Security/security_officer.yml

adds the ClothingBlockSlotsOnEquipComponent to the plate carrier and makes it block outerClothing, while also giving it the same stats as the armor vest
makes it use the sec belt fill and changes the loadout to use the filled version
fixes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/452
<details><summary>Click me!</summary>
<br>
gottem
</details>

security plate carrier improvements

---

Resources/Locale/en-US/_CD/engraving/engraving.ftl

Hey-hey! This is a tiny change that adds a space behind the colon in the dogtag engraving description.
Found this while I was porting the dogtag stuff to Delta, so I thought I'd add it here too so people don't have to awkwardly put a space in front of your engraving message any longer.
- Tiny change in engraving.ftl
n/a
n/a
**Changelog**
The format of the dogtags engraving message has been slightly improved!

Add space behind the colon in the dogtag description

---

Resources/Prototypes/Procedural/salvage_loot.yml

Salvage rewards pool hasn’t been used for almost a year so removing cloning boards from there didn’t do anything
Removing the static cloning parts in each of the salvage dungeon templates would require editing maps and I am NOT touching that
Why is nothing in this file sorted???????

Removes cloning boards from expedition loot pool

---

.github/workflows/cd-build-upload-artifact.yml

Created a workflow to generate server artifacts that can be used by non-technical users to create a local instillation of CD.
Example of it working: https://github.com/dffdff2423/cosmatic-drift/actions/runs/12331887366
**Changelog**
We now have automatic server builds so you can test things locally. Please follow the [attached guide](https://gist.github.com/dffdff2423/e1b10f5e163840b364e64aa828fe54b7) for how to download and set them up.

Add workflow for easy to use servers.

---

Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/box.yml
Resources/Prototypes/Maps/cog.yml
Resources/Prototypes/Maps/core.yml
Resources/Prototypes/Maps/marathon.yml
Resources/Prototypes/Maps/meta.yml
Resources/Prototypes/Maps/oasis.yml
Resources/Prototypes/Maps/packed.yml

This changes the role slots of several Upstream maps.
Any bartender count was brought down to 1-2 if it didn't have a second set of dispensers.
All intern roles were reduced to 2-2.
Doctors were reduced to 3-3 except for Meta, Box, and Oasis which have 4-4.
Any chemist slots above 3 were reduced to 2-2.
Cargo techs were set to 3-3 if they exceeded 3.
Core got an extra lawyer, just because having two is more interesting.
This is mostly playing it by touch in an effort to declutter some departments like medbay which have recently had an influx of complaints, also a couple adjustments made to the other roles from my personal experience.
Not touching any CD map because that's up to their respective maintainers.
**Changelog**
Most maps have gotten slightly readjusted job slots, the biggest …

Role Slot Adjustments

---

Resources/Locale/en-US/_CD/prototypes/roles/antags.ftl
Resources/Prototypes/_CD/Roles/Antags/preferences.yml

Added preferences so players can opt-in to being antag targets.
This is mainly so admins don't need to bwoink players and spoil that they are a target.
I prefixed the locale string for each antag pref with a number. This is because the game sorts them alphabetically. It looks *much* better than the alternative.
**Changelog**
You can now opt-in to being intentionally targeted for general antagonistic activity and round removal under the antag tab in the character creator. Keep in mind not enabling this will not prevent harm from befalling you throughout normal gameplay (our minor crimes rule still applies).

Add antag target preferences.

---

Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/_CD/Recipes/Lathes/medical.yml

The handheld crew monitor can now be found in the paramedic's locker roundstart, or printed using 6 steel, 6 glass, 6 plastic and 3 gold at the medfab.
I played a round of paramedic to try and be a bit more active around the station, I felt even more glued to medical than I did as a normal doctor because of the crew monitor. There can be a sudden catastrophe in sci from artifacts, because of sci from anomalies, or just entirely random and unrelated from some guy falling out an airlock. Even in a HRP environment the game can suddenly be chaotic as ever, so giving the paramedic at least something to allow them freedom of movement without significantly hindering themselves is nice.
I feel like medical in general has a lot of issues with being glued to their department and unable to get out …

Paramedics get the handheld monitor and it can be printed at the medfab

---

Resources/Locale/en-US/_CD/traits/traits.ftl
Resources/Prototypes/Traits/quirks.yml
Resources/Prototypes/_CD/Traits/categories.yml
Resources/Prototypes/_CD/Traits/traits.yml

Add Very Lightweight and Heavyweight drunk traits
I think it is fine to have a Heavyweight drunk trait because it is mainly an RP thing. It is basically impossible to get drunk without the players consent anyways.
I also created a category for them so that you can only have one drinking skill trait at a time.
**Changelog**
Added the Heavyweight and Very Lightweight drunk traits. You can only have one Alcohol Tolerance trait at a time.

Very Lightweight and Heavyweight drunk traits

---

Content.Server/_CD/Records/RecordsSerialization.cs

I am not able to reproduse it locally. This is a bit of a shot in the
dark based on the results of messing around with the rider postgres browser.
When I originally wrote the code I assumed that SQL queries would automatically
order by ID. I think I might be wrong about this, so I forced it to order them
by id which *should* fix the issue.
**Changelog**
Records entries should hopefully no-longer change their order semi-randomly. Please let us know if the issue still persists.

First attempt at fixing the record order bug

---

Content.Shared/CCVar/CCVars.Shuttle.cs

Our arrivals map does not support planets, and it seems to cause release builds 
to not get in-game unless you set this cvar to false. This is already set on the 
server and probably should be set in the repo in-order to stop being a footgun.

Disable planet arrivals.

---

Resources/CDMapPatches/amber.yml
Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/Maps/amber.yml

Adjusts Amber's prototype to fit CD standards, including the CD roles and more fitting pop count (5-25).
Adds an Amber map patch for a lost and found locker in the bridge, and a medical records computer in the treatment bay.
25 max may be a *tad* bit small role wise. It's more like Core and Aspid in terms of that. But size wise it's more like Omega, Packed, etc, so I went with that instead.
**Changelog**
Amber has been updated to fit CD and now will appear between 5 and 25 population.

Amber CD Port

---

Resources/Prototypes/_CD/Entities/Objects/Devices/Circuitboards/computer.yml
Resources/Prototypes/_CD/Entities/Objects/Devices/flatpack.yml
Resources/Prototypes/_CD/Entities/Structures/Machines/Computers/computers.yml

Gives the job slots console a computer board and flatpack.
I want to use it for mapping reasons.
**Changelog**
Nada. Bit small for one.

Job Slots Computer Board and Flatpack

---

Content.Server/_CD/Honeypots/AdminNotifyOnDamageComponent.cs
Content.Server/_CD/Honeypots/AdminNotifyOnDamageSystem.cs
Resources/Prototypes/_CD/Entities/Objects/Honeypot/glass.yml

We have a room of valuables on the arrivals terminal that raiders often go for. This PR enables mappers to notify admins if the room is broken into. This should be mapped in the arrivals terminal.
**Changelog**
None, it is not mapped yet.

Add honeypot glass

---

Resources/Prototypes/GameRules/unknown_shuttles.yml

Generally better to have this be quiet imo, especially as the ghost roles being taken is super unlikely. Hailing channel also solves this issue & leads to more RP.

Remove the unknown shuttle announcement. 

---

Content.Client/_CD/Engraving/EngraveableSystem.cs
Content.Server/_CD/Engraving/EngraveableSystem.cs
Content.Shared/_CD/Engraving/EngraveableComponent.cs
Content.Shared/_CD/Engraving/SharedEngraveableSystem.cs

basically the changes i did in https://github.com/emberfall-14/emberfall/pull/12 anyways so no reason not to PR it here too
moved the examine part to shared and networked the text so that you dont have to wait one second and watch it change from the "nothing engraved" text to "custom message" text in real time

make dogtags text predicted

---

Resources/Prototypes/_CD/Loadouts/role_loadouts.yml

Voxes as a Senior Officer no longer start with a tank harness, and instead start with their selected outer clothing equipped.
Fixes #498
I was bored
Just comments out `GroupTankHarness` like I did for vox detectives on upstream. I can't do this fix on upstream and have you guys merge it as SeniorOfficer roles don't exist for upstream.
**Changelog**
I'm doing this in the style of an upstream CL
🆑 
- fix: Senior Officer Vox now start the shift with their selected outer clothing equipped. Previously it would be overridden by a tank harness and your clothing would start on the floor.

Bugfix: Senior officer vox start with their selected outerclothing

---

Resources/Prototypes/Entities/Markers/Spawners/Random/posters.yml
Resources/migration.yml

Remove posters that can be seen as LRP-ish.
Deathsquad recruitment -> We want death squad to be a more mysterious thing.
Lusty Xenomorph Maid -> Why does this exist on a 16+ codebase. Thanks wizden.
No ERP poster -> ERP is not a IC term.
Busty Backdoor Exo Babes -> Why is this in a game that is intended to be rated 16+?! If somebody said the description in-game they would likely get banned.
Disabled them in the random spawner and migrated them out in case any maps use them.
**Changelog**
A few LRP posters have been removed.

1984 LRP posters

---

Resources/CDMapPatches/convex.yml
Resources/Prototypes/Maps/convex.yml

Changes Convex station.
- Adjusts the player minimum to 45.
- Adds CD senor roles.
- Adjusts Upstream role counts. (Of note, security officer is set to 4-4 instead of the regular 3-3 because it's a sizable map)
- Adds map patches for CD entities.
**Changelog**
Convex station has been updated to match CD and now appears at 45+ player population.

Convex CD Port

---

Resources/Prototypes/_CD/Entities/Mobs/Species/avali.yml

Adds the missing thermal slowdown values to Avali
Adds missing values to avali.yml, adjusted to match the species stats.
**Changelog**
Avali are no longer slowed down until much colder then other species.

Avali Thermal slowdown fix

---

Resources/Prototypes/_CD/Recipes/Lathes/Packs/cdpacks.yml

Added missing wheelchairs to medical lathes.
They were missing due to the recent lathe pack change (I think?).
Added VehicleWheelchairFolded to CDMedfabStatic
N/A
**Changelog**
Wheelchairs can now be made again at medical lathes

Added Wheelchairs to Medical Lathes

---

Resources/CDMapPatches/amber.yml
Resources/CDMapPatches/bagel.yml
Resources/CDMapPatches/box.yml
Resources/CDMapPatches/convex.yml
Resources/CDMapPatches/core.yml
Resources/CDMapPatches/elkridge.yml
Resources/CDMapPatches/loop.yml
Resources/CDMapPatches/marathon.yml
Resources/CDMapPatches/meta.yml
Resources/CDMapPatches/oasis.yml
Resources/CDMapPatches/omega.yml
Resources/CDMapPatches/packed.yml
Resources/CDMapPatches/plasma.yml

Updates all current CD map patches to include the newest stuff. Including Pebble.
**Changelog**
Pebble, the Argocyte pet, will now spawn on all Upstream maps. Additionally all upstream maps should now have the job slots console and salvage shuttle consoles.

Map Patch Maintenance

---

Resources/Prototypes/_CD/Loadouts/loadout_groups.yml

Adds Trooper Gear (including the hat obviously, for the drip) to Senior Officer Loadouts.
**Changelog**
Senior Officers can now wear Trooper Gear for that added security drip.

Added: Trooper Gear for Senior Officer Loadouts

---

Content.Server/Disposal/Tube/Components/DisposalTubeComponent.cs
Content.Server/Disposal/Unit/EntitySystems/DisposableSystem.cs

Title, adds disposal damage with a cap. The numbers were based on some testing on fland.
**Changelog**
Disposals now deals damage, however it will not continue to hurt you once you are dead.

Add disposals damage with a cap.

---

Content.Server/Dragon/DragonSystem.cs
Resources/Locale/en-US/dragon/dragon.ftl
Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/Entities/Mobs/Player/dragon.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/Objectives/dragon.yml
Resources/Prototypes/Roles/MindRoles/mind_roles.yml

Re-enables the Space Dragon event at weight 1 because it was fixed Upstream to not delete bodies on butcher.
Also makes it a free agent and disables the 5 minute timer that deletes the dragon when no rifts are active. (Technically a buff.)
_What's the worst that could happen..?_
**Media**
**Changelog**
Space Dragons can now very rarely appear as a ghost role again and attempt to either conquer or befriend the station.

Re-enable Space Dragons

---

Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/loadout_groups.yml

- Fixes Interns not showing up in their departments on crew monitoring.
- Fixes roboticist PDA not being selectable.
- Cleans up some no longer used code related to the roboticist PDA.
**Changelog**
Interns show up properly on the crew monitor and the roboticist PDA can be selected again.

Fix Title PDAs

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs

fixes admin record console not showing the proper record entries when you select an entry filter (for filtering security, employment, or medical records)
**Changelog**
ADMIN: the admin records console now actually lets you filter what records you want to look at again via record type

admin records console can filter by record entry type again

---

Resources/Prototypes/Roles/Jobs/Medical/chief_medical_officer.yml
Resources/Prototypes/Roles/Jobs/Science/research_director.yml

- Gives the RD and CMO externals access like the rest of command.
---
- RD has a valid use for externals due to #570 and needing to access the AI core without harming themself if it's not an emergency.
- CMO is given it because they'd become the only head without externals which is a bit weird, but it has some merit if search and rescue needs to be conducted with no paramedics. We should be able to handle CMOs who step on the toes of their own paramedics or abuse this access.
- In general I think it makes sense that the heads of staff on a space station all can be trusted to have access to the front doors.
**Changelog**
CMO and RD now have externals access.

Head of Staff Externals Access

---

Resources/Prototypes/Catalog/Cargo/cargo_armory.yml
Resources/Prototypes/_CD/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/_CD/Catalog/Fills/Crates/medical.yml
Resources/Prototypes/_CD/Entities/Objects/Misc/implanters.yml
Resources/Prototypes/_CD/Entities/Objects/Misc/subdermal_implants.yml

Adds a crate of medical tracking implants, entirely identical to security tracking implants apart from three factors;
- They come in a secure medical crate.
- They transmit over the medical channel.
- They only rattle off when the user experiences full death opposed to entering critical condition.
Also increases the price of security trackers to 2500 from 1000. Med trackers cost the same as well.
**Changelog**
You can now order medical tracking implants from cargo as an alternative to security tracking implants. Security tracking implants also cost $2500, upped from $1000.

Med Tracking Implants

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/cart.yml

- Adds common, command, and hailing encryption keys in the PTech vendor.
- Increases all encryption key amounts to 3.
---
- Having a way to get more command and hailing keys feels important. Hailing especially for giving high command greater ability to delegate hailing matters to other heads or just keeping them in the know directly if desired.
- We shouldn't have to worry too much about the potential abuse from having a few more encryption keys in the vendor, it kind of bothered me that there were so few for things like security.
**Changelog**
The HoP now has access to spare common, command, and hailing radio encryption keys in their PTech vendor.

More Radio Keys in PTech

---

Resources/Prototypes/_CD/Entities/Mobs/Customization/Markings/synthetic.yml

why was this flag even set in the first place? coloring the synth tail works perfectly fine, why not allow it? what's the worst that can happen?
the whole tail should really be resprited to have top and underbelly color zones like the rest of the but that's above my paygrade so have this band aid instead
(reposted because i'm so good at git, i think this is right now)
- [ X ] I have read and I am following the Cosmatic Drift [PR Guidelines](https://github.com/cosmatic-drift-14/cosmatic-drift/blob/master/CONTRIBUTING.md) (note that they may differ than what you find on other SS14 forks).
- [ X ] I have approval from a maintainer if this PR adds a feature OR this PR does not add a feature OR you are alright with this PR being closed at a maintainer's discression.
- [ X ] I have added …

make the lizard synth tail not arbitrarily uncolorable (again)

---

Resources/Prototypes/Species/arachnid.yml
Resources/Prototypes/Species/diona.yml
Resources/Prototypes/Species/human.yml
Resources/Prototypes/Species/moth.yml
Resources/Prototypes/Species/reptilian.yml
Resources/Prototypes/Species/slime.yml
Resources/Prototypes/Species/vox.yml
Resources/Prototypes/_CD/Species/avali.yml
Resources/Prototypes/_CD/Species/rodentia.yml
Resources/Prototypes/_CD/Species/vulpkanin.yml

Increased the marking limits of all roundstart species to 4 for chest and 6 for arms and legs except for species that don't have enough markings to reach this number because the tests were crying. 
Vox don't get any extra because they don't have that many markings anyways and whenever I touch them they explode.
If we can have lizard hair we can have more markings.
Player expression etc.
**Changelog**
Many species can now choose more chest, arms, and legs markings.

add creativity by increasing marking limits

---

Resources/Prototypes/Entities/Objects/Specific/Kitchen/foodcarts.yml

Increased the capacity of the food cart from 30 to 300, as per discussion here https://discord.com/channels/1163352113162768436/1364763014074728480, since it's kinda hard to practically use with such a low capacity. Left unwhitelisted to allow for traitor shenanigans (rolling up to the bridge with 'food' for command :3)
**Changelog**
BlueNexa: Increased capacity of the food carts from 30 to 300.

Increased food cart capacity to 300

---

Content.Shared/Ghost/GhostComponent.cs

Simply accidentally removed AutoNetworkedField during the (2nd) last upstream merge.

fix ghost respawn button timer

---

Resources/Prototypes/Guidebook/rules.yml

It uses new wizden space law. We should remove it to not confuse people.

Remove crimelist from guidebook

---

Resources/Locale/en-US/_CD/engraving/engraving.ftl
Resources/Prototypes/Entities/Clothing/Hands/base_clothinghands.yml

Rings can now be engraved like dog tags!
Why?
I think it's neat, and it's a harmless change, can add more flavor to rings! 
**Changelog**
Rings can now be engraved like dog tags.

Make Rings able to be engraved

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/atmosdrobe.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/engidrobe.yml
Resources/Prototypes/Entities/Clothing/Uniforms/jumpskirts.yml
Resources/Prototypes/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Entities/Clothing/Uniforms/jumpskirt.yml
Resources/Prototypes/_CD/Entities/Clothing/Uniforms/jumpsuits.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Engineering/atmospheric_technician.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Engineering/station_engineer.yml

Made duplicated versions of the Engineering uniforms to let people use both the original and redesigned versions
**Changelog**
Gave back the older engineering uniforms, don't forget to pick your preference in the loadout!

Cosmetic Drip 4.3 ~ Derespriting Engineering

---

Content.Shared/Telephone/TelephoneComponent.cs

increase the time it takes for a holopad to timeout from idleness from 1 minute to 10 minutes
(primarily as AI) it gets really annoying to constantly be hanged up automatically because you're listening to someone talk from the other end of the holopad and you don't want to interrupt
changes the default TelephoneComponent value for the timeout time to 10 minutes due it probably being something that we don't want to have issues with in the future should anything else that uses the component be merged
physically cannot attach a video that would show this due to the length
**Changelog**
Holopads now take longer to kick you out of a call for being idle.

increase idle timeout from 1 to 10 minutes for holopads (and all things using TelephoneComponent)

---

Resources/Prototypes/Entities/Mobs/Player/silicon.yml

gave the AI the ability to be hit by ion storms
apparently it was something that was wanting to be done but was simply never done? this hopefully remedies that, and means more interaction with the AI in the future by using the boards in the upload (and probably having some conflict)
do note that this uses the default ion chance of being affected (which is 80%) so if it is too much, it should probably be lowered at a future point
**Changelog**
AI cores can now be affected by ion storms, hurray!

make AI ion storm vulnerable

---

Resources/Locale/en-US/_CD/markings/vulpkanin.ftl
Resources/Prototypes/Entities/Mobs/Customization/Markings/scars.yml
Resources/Prototypes/Entities/Mobs/Customization/Markings/tattoos.yml
Resources/Prototypes/Entities/Mobs/Customization/Markings/undergarments.yml
Resources/Prototypes/_CD/Species/vulpkanin.yml

Fixes a lot of weird marking issues from vulps.
Vulps now have access to: The Undergarment markings, the left/right eye markings (heterochromia), the human scars, their overlay marking limit has been increased from 2 -> 6, and the tails without wagging animations now have (No Wag) in their locale, to help with confusion.
Chips away at the vulpkanin improvement issue.
**Changelog**
Vulpkanins now have access to a broader set of options as markings and the tails without wagging animations have been marked as such.

Vulpkanin Marking Improvements

---

Content.Server/Administration/Commands/AdminWhoCommand.cs

Unrestricted the `adminwho` command so that players have an easier time with event plans or other things.
**Changelog**
Everyone now has access to the adminwho command which allows you to see which admins are currently admining.

Adminwho for all

---

Content.IntegrationTests/Tests/_CD/CharacterImportTest.cs
Content.Shared/_CD/Records/PlayerProvidedCharacterRecords.cs

Added null checks for values that can end up as null when importing old characters. I also added a regression test (90% of the PR lol).
**Changelog**
Importing old CD characters should be fixed.

Fix backwards compatibility for CD char imports

---

Content.Server/GameTicking/GameTicker.RoundFlow.cs

Because most players do not take the trait it has basically the opposite effect. All of the players with a redacted name are listed at the start of the round-end screen. This changes it so they are removed from the manifest post round. 
**Changelog**
no cl no fun

Improve redaction trait

---

Resources/CDMapPatches/exo.yml
Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/Maps/exo.yml

-Adds the Exo map patch for CD stuffs.
-Adds all the CD stuff to Exo. Including a prisoner slot.
-Removes the intern roles and adjusts the base department job slots accordingly.
-Sets the map at Marathon and Bagel pop; 25-55. Something I'm conflicted about due to a whole series of reasons but I went with my gut here.
**Changelog**
Exo Station has been updated to fit CD standards and is now in rotation.

CD Exo Update

---

Resources/Prototypes/_CD/Entities/Mobs/Species/vulpkanin.yml

When adding their access to the markings, I forgot to actually make it so they'd draw the layers. Meaning that you'd select the markings but they would not display.
This adds both the layers to them (based off what the other species do).
**Changelog**
fix: Vulpkanin Undergarments will now display.

[Bugfix] Add Undergarment Layers to Vulps

---

Resources/Prototypes/_CD/Traits/traits.yml

_This PR has been moved from https://github.com/Sector-Umbra/Sector-Umbra/pull/391. I would rather this fix for more servers than just Umbra._
Ethanol currently is the only main source to making people drunk in SS14. Currently, it has booze power of 2. This means that for every tick it runs in your system, it gives you about 2 seconds worth to a status effect for Drunk. 
The issue with Heavy weight, is that it halfs this to 1 seconds. The issue with this, is that it calculates when you are drunk based on how much of timer you have compared to the current time. So no matter how much ethanol you have in your system, you should feasibly never be able to get drunk.
This changes it so instead of halfing this time, it only does 0.75x. So therefore, if someone were to remain with ethanol in …

Balancing the Heavy Weight Trait

---

Content.Server/_CD/Loadouts/RenameIdComponent.cs

This fixes the issue of passenger IDs showing up blank when off-duty staff was selected.
**Changelog**
Off-Duty staff IDs once again have the passenger icon as intended.

Fix RenameIdComponent defaulting to Blank ID

---

Resources/Prototypes/Entities/Clothing/Back/satchel.yml

Satchels of holding were broke so I fixed them. It was only satchels nothing else.
**Changelog**
Satchels of holding have their correct size once again.

Fix Satchels of holding

---

Content.Server/GameTicking/GameTicker.RoundFlow.cs
Content.Server/_CD/Traits/HideFromRoundEndScreenComponent.cs

Added an additional check for observers this also covers admin spawned characters.
Closes: #719
**Changelog**
Observers and admin spawned characters with the Hide OOC Name trait will no longer be listed in the round end screen.

Anonymize observers with the hidden name trait

---

Resources/Prototypes/Entities/Mobs/NPCs/human.yml

Makes all the corpses found during salvaging unrevivable. Also makes the syndicate shuttle pilot unrevivable.
The former is way more lore friendly with how the Fissure is supposed to ruin the DNA of nearly all the corpses that spawn from it.  And as for the shuttle pilot and a bit of the corpses, there's just not really any reason to leave the option on the table, reviving either of these results in a soulless husk that kind of just stands around.
**Changelog**
The syndicate shuttle pilot and corpses from salvage wrecks are no longer revivable.

Lore Friendly Salvage Corpses

---

Resources/Locale/en-US/mind/components/mind-component.ftl

Changed the descriptions for soulless and catatonic players to explain that they will recover, just not on the station. This is so that ~~i can get contrib role :3~~ players don't get confused about how to deal with catatonic and soulless players. 
Changes are below. CC having the magic, catatonic revival medicine or treatment seems fine enough. Cryopods probably bring you to CC or could be brought to CC, and obviously the evac shuttle brings you to CC. 
Encouraging players to revive soulless people seems like the right thing to do. It's probably easier to wake up an alive but catatonic person, rather than cloning someone from scratch, because the players didn't know they needed to be revived.
**Changelog**
Changed the description of catatonic and soulless players.

Catatonic and Soulless description changes

---

Content.Client/Clothing/ClientClothingSystem.cs
Content.Shared/Clothing/EntitySystems/HideLayerClothingSystem.cs
Resources/Prototypes/Entities/Mobs/Species/moth.yml
Resources/Prototypes/Entities/Mobs/Species/reptilian.yml

Disables lizard hardsuit body sprites.
While the sprites created in https://github.com/space-wizards/space-station-14/pull/35842 look great, they kind of break continuity with lizards that have large tails (from wizden), or the tails added in #527 (which are a fairly popular option).
Sooner or later, I wager somebody will code a proper hardsuit marking system which would fix this issue.
Disabled using a few wads of shitcode rather than editing the meta files to prevent merge conflicts.
I also went and made Moth and Lizard hair get hidden upon using a hardsuit helmet. Probably should have been a separate PR but too late now.
**Changelog**
- Temporarily (possibly permanently) disable the lizard hardsuit sprites until a more robust hardsuit marking sprite system is created.
- Moth and Lizard …

Disable lizard hardsuit bodies and hide hair

---

Resources/Prototypes/Entities/Objects/Materials/Sheets/metal.yml

Probably broken in an upstream merge.

Fix stack size for 1 plasteel.
