Resources/Prototypes/Hydroponics/seeds.yml

make all plants take longer to mature and also increase their lifespan as well as idk if i did it correctly but i doubled the nutriment/water numbers too in the hopes it would increase their longevity as well but i cant tell i'm math deaf :trollface: 
LRP-paced plants suck I can't RP without my damn plants dying, also the times could definitely be increased more but i dont understand the code behind the maturation rate
values in a prototype
**Changelog**

botany gaming but LONGER

---

Content.Server/_CD/Spawners/ArrivalsSpawnPointComponent.cs
Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs
Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml

forces anyone who spawns (with the respective job) to be teleported there. fun.

Adds arrivals spawn points

---

Resources/Locale/en-US/game-ticking/game-ticker.ftl

"John Engineering (Chief Medical Officer) has been assigned to the shift."
"A shuttle transferring you to your station will arrive at the southern docks shortly."
Better fitting for lore!!!11!!1

Better Arrivals Messages

---

Content.Server/_CD/CryoSleep/CryoSleepSystem.cs
Resources/Locale/en-US/_CD/cryosleep/cryosleep-component.ftl

announcement code isn't ideal but if it works, it works.

Cryo Pods clear manifest + announce

---

Resources/Prototypes/Catalog/Cargo/cargo_emergency.yml
Resources/Prototypes/Catalog/Cargo/cargo_medical.yml
Resources/Prototypes/Catalog/Cargo/cargo_science.yml
Resources/Prototypes/Catalog/Cargo/cargo_security.yml
Resources/Prototypes/Catalog/Cargo/cargo_service.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/bio.yml
Resources/Prototypes/Reagents/botany.yml
Resources/Prototypes/Reagents/cleaning.yml
Resources/Prototypes/Reagents/elements.yml
Resources/Prototypes/Reagents/toxins.yml

Chemical effects pass.
Changed a bunch of chemicals to make them feel interactive. Acids deal much more damage while splashed on people, because they're acids and the old damage values were really underwhelming even when throwing bluespace beakers or using backpacks full of acid to shoot acid at people. Every element that is caustic or irritable in real life is now dangerous to spill or slip in. Lab coats and PPE, people.
Amatoxin was also reworked to be a slower killer. 9u will crit someone but it will take about 100 seconds. Dying silently really fast via poison isn't great for RP in my opinion and Amatoxin as always been overkill. It now serves as a bridge between lead and other poisons.
Bio suits have been buffed to help protect janitors and others from chemical threats.
HRP, …

painful chemicals

---

Resources/Prototypes/Entities/Clothing/Shoes/boots.yml

Updates the jackboot description to be more consistent with them no longer having storage.

Update Jackboot Description

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/human_hair.yml
Resources/Prototypes/Species/reptilian.yml

Lizard Hair.

---

Content.Server/Connection/ConnectionManager.cs
Content.Shared/CCVar/CCVars.cs
Resources/Locale/en-US/connection-messages.ftl

this might break shit so be ready to revert

Soft Whitelist Addition

---

Content.Server/Connection/ConnectionManager.cs

THIS might also need to be reverted. We'll see.

Fix the soft whitelist

---

Content.IntegrationTests/Tests/Construction/Interaction/WallConstruction.cs
Content.IntegrationTests/Tests/DoAfter/DoAfterCancellationTests.cs
Resources/Prototypes/Recipes/Construction/Graphs/structures/girder.yml

Make Building Walls Take Welding Part Two

---

Content.Server/StationEvents/BasicStationEventSchedulerSystem.cs
Resources/Prototypes/GameRules/events.yml

Makes some of the more disruptive ones less common, and makes events on average happen less often.

Tune Events

---

Content.Server/Stack/StackSystem.cs
Content.Shared/Storage/EntitySystems/SharedStorageSystem.cs

Known issue that the UI doesn't update, no idea why. Will worry about it later.

Fix Stacking Bug

---

Resources/Prototypes/GameRules/events.yml

Remove rat king event

---

Resources/Prototypes/game_presets.yml

Annoying, and probably going to cause issues one day.
HRP Death Match Server, my favorite.
**Changelog**
Funnier if only the people who pay attention to the repo figure out.

Disable Sandbox and DM

---

Resources/Locale/en-US/_CD/reagents/RPmeds.ftl
Resources/Locale/en-US/_CD/reagents/meta/medicine.ftl
Resources/Locale/en-US/_CD/reagents/meta/physical-desc.ftl
Resources/Prototypes/_CD/Reactions/medicine.yml
Resources/Prototypes/_CD/Reagents/medicine.yml

I decided to atomize RP meds because they ended up being more complicated than I thought.
This PR adds 6 medicines that are primarily RP-based. Their main purpose is to act as meds that characters may need to take to deal with emotional issues. They give RP prompts that you may or may not follow, which get wackier if you overdose. There are a few cool overdose effects ranging from short-term paralysis to psychosis. They have a lot of interactions and are all pretty fleshed out I think. They all are detailed automatically in the Chemicals section of the guidebook, and can be found by searching for "Anxiety" or "Antidepressant." Their guidebook descriptions detail on how they work fairly well. 
These chemicals are **primarily** for RP value and do not yet provide any mechanical advantage …

Antidepressants and Anxiety RP Meds

---

Resources/Prototypes/_CD/Reactions/medicine.yml

i accidentally made it make something else 
:cl:
- fix: The tranquinase recipe has been fixed

tranquinase recipe now makes tranquinase 

---

Content.Client/Options/UI/Tabs/MiscTab.xaml
Content.Client/Options/UI/Tabs/MiscTab.xaml.cs
Resources/Locale/en-US/escape-menu/ui/options-menu.ftl

Someone forgor to comment it out
**Changelog**
No need

Comment out the remaining gridinv general settings

---

Resources/Locale/en-US/_CD/job/job-description.ftl

fix prisoner role description 

---

Resources/Prototypes/Maps/aspid.yml

Add prisoner role to aspid

---

Resources/ServerInfo/Rules.txt

Outlaws arrivals grief.
Adds new rule for leaving as a command role or while undergoing in-character punishment
**Changelog**
The rules have been updated.
Clarification that arrivals is off-limits for any sort of antagonistic acts.
New ruling for leaving as a command role or while undergoing in-character punishment. Just ahelp before hand if you can is all we ask.

Rules Update 29-12-2023

---

Resources/Prototypes/GameRules/cargo_gifts.yml
Resources/Prototypes/GameRules/events.yml
Resources/Prototypes/threats.yml

in the wise words of flareguy, what it says on the tin

lower pizza event weights, raise others, disable dragon & rod 

---

Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml

Adds an arrival spawn point for Bartender, Clown, Librarian, Mime and Musician.
Required for #109

Service Arrival Spawns

---

Content.Shared/CCVar/CCVars.cs

#106 
It was a test to see if it'd work, it didn't.

Revert "Extend Round End Time"

---

Resources/Prototypes/_CD/Roles/Jobs/Wildcards/prisoner.yml

It exists, already accessible from the wardrobes, don't see why not.

Fix Prisoner Skirt Selection

---

Content.Server/Ghost/GhostSystem.cs
Content.Shared/Ghost/GhostComponent.cs
Content.Shared/Ghost/SharedGhostSystem.cs

Fixes #133 
Adds the required annotations and dirtying to sync the death time to the client.
**Changelog**
This is probably too minor to warrant a post in discord.
:cl: Aquif
- fix: The respawn button now counts down properly

Fix respawn button cooldown

---

Resources/clientCommandPerms.yml

I really don't care about people not reporting issues or w/e

Revert "Put entity resetting behind command flag (#24436)"

---

Content.Client/_CD/Records/UI/RecordEditorGui.xaml
Content.Shared/_CD/Records/CharacterRecords.cs
Resources/Locale/en-US/_CD/records/editor.ftl

People on discord were confused by the intent of this field. This clarifies the intent and increases the character limit to the same as all of the other fields.
**Changelog**
N/A

Clarify the intent of the contact name record

---

Content.Client/_CD/CryoSleep/AcceptCryoWindow.cs
Content.Client/_CD/CryoSleep/CryoSleepEui.cs
Content.Server/_CD/CryoSleep/CryoSleepComponent.cs
Content.Server/_CD/CryoSleep/CryoSleepEui.cs
Content.Server/_CD/CryoSleep/CryoSleepSystem.cs
Content.Shared/_CD/CryoSleep/AcceptCryoSleepEuiMessage.cs

See title. Also moves all of the CryoSleep stuff into the CD namespace.
**Changelog**
Not user facing

Fix ContainerSystem deprications in CryoSleepSytem

---

Content.Client/_CD/Records/UI/CharacterRecordConsoleBoundUserInterface.cs
Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs
Content.Client/_CD/Records/UI/RecordEntryViewPopup.xaml.cs
Content.Server/_CD/CryoSleep/CryoSleepSystem.cs
Content.Server/_CD/Records/CharacterRecordKeyStorageComponent.cs
Content.Server/_CD/Records/CharacterRecordsComponent.cs
Content.Server/_CD/Records/CharacterRecordsSystem.cs
Content.Server/_CD/Records/Consoles/CharacterRecordConsoleComponent.cs
Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
Content.Shared/_CD/Records/CharacterRecords.cs
Content.Shared/_CD/Records/FullCharacterRecords.cs
Content.Shared/_CD/Records/SharedCharacterRecordConsole.cs
Resources/Locale/en-US/_CD/records/editor.ftl

Improves the character records code, and makes the UI a bit less jank. Also, properly remove records when the player cryosleeps.
Using EntityUid as a key in the record storage did not work very well and caused all sorts of issues. Moving to integer keys is a more proper fix for the major issue fixed in #152 and hopefuly should fix some other minor bugs. The "duplicate keys error" should **never** occur anymore. 
**Changelog**
Mostly not user facing, other than fixing some UI jank.

Character records backend improvements and minor UI fixes

---

Resources/Prototypes/Entities/Mobs/NPCs/animals.yml
Resources/Prototypes/Entities/Mobs/NPCs/simplemob.yml

I lowered the hunger decay rate to match the thirst decay rate. I also made simplemobs able to pull things, with or without hands.
> rat metabolism is so high, way too high to RP. By the time I show my appreciation to the lovely chefs who gave me food, I'm already starving again! I end up just ignoring food all together.
Simply lowers the hunger decay rate and adds the puller component to SimpleMobs
**Changelog**
:cl:
- tweak: Mice now need to eat less often.
- tweak: All animals can now pull things.

[Tweak] Mouse hunger modification and SimpleMob pulling

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml
Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs
Content.Client/_CD/Records/UI/RecordLongItemDisplay.cs
Content.Shared/_CD/Records/CharacterRecords.cs
Resources/Locale/en-US/_CD/records/viewer.ftl

Improves the UI of short answer records by placing the record on a new line if the text is above a certain length. This removes quite a bit of jank from the UI and permits us to re-increase the cap for "short answer" records from 64 to 128 characters without breaking the UI.
We also make it possible to press enter on the record search bar to search.
This was the original length I wanted all along, just that the UI broke when records were too long. This also improves the handling of old long records because the cutoff for a line break is 1/2 of the previous cap. 
Create a new Widget  to manage long record items. This widget decides if a record should be displayed as a long item or a short item and automatically adjusts itself.   
**Changelog**
:cl: Aquif
- tweak: All three character record …

Improve the records UI to support longer "short answer" character records

---

Resources/Prototypes/_CD/StatusEffects/job.yml

Not 100% that this is the reason but it should be why.

Fix the PI role icon

---

Resources/ServerInfo/Rules.txt

BetterRules(tm)

---

Resources/Prototypes/_CD/Entities/Clothing/Head/helmets.yml
Resources/Prototypes/_CD/Entities/Clothing/Masks/masks.yml
Resources/Prototypes/_CD/Entities/Clothing/OuterClothing/harnesses.yml
Resources/Prototypes/_CD/Entities/Clothing/Uniforms/jumpsuits.yml

Changes "etu" into "ETU" for abbreviation conformity
It fits with the ERT abbreviation and makes it more uniform instead of being all lowercase, it looks out of place
**Changelog**
:cl:
- tweak: Reabbreviates "etu" into "ETU" for abbreviation conformity

Abbreviates "etu" into "ETU"

---

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml

Fix Cargo Arbitage

---

Resources/ServerInfo/Rules.txt

Adds some clarification to the Non-English rules.

Non-English Rules

---

Content.Client/Options/UI/Tabs/MiscTab.xaml

HudLayoutOptions appeared twice.

Fix options menu. Hopefully.

---

Content.Client/Options/UI/Tabs/MiscTab.xaml

Fixes the options menu and hide some gridinv related options.
It looks like some code was not properly deleted in the upstream merge. [this](https://gist.github.com/dffdff2423/f21f0a30fb421ecb286c3ef5ac184db0) is the diff with upstream for the options directory after this PR would be applied.

Fix options menu

---

Resources/ServerInfo/Rules.txt

Sub-bullet of 4.6.
"You cannot take direct, unchallengeable orders from people other than your job superiors."

Control Rules

---

Resources/Prototypes/Entities/Structures/Machines/lathe.yml
Resources/Prototypes/Recipes/Lathes/clothing.yml

Added all of the seven pride cloaks to the uniform printer
to be able to hand out pride cloaks at request, it felt like a nice addition.
**Changelog**
-add: Added Pride Cloaks to the Uniform Printer

Gives the uniform printer pride cloaks

---

Content.Client/_CD/Records/UI/RecordEditorEntrySelector.xaml

Joined earlier and saw the corners not filled and it was bothering me

Fit the Records Add and Down Buttons to their Container

---

Resources/Maps/_CD/ferrous.yml
Resources/Maps/gemini.yml

woo actually fixed yae (no rubbers on kettle and ferrous fr this time lads)

---

Content.Client/_CD/Records/UI/CharacterRecordConsoleBoundUserInterface.cs
Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs

Wizden added some new security statues that required some minor
alterations to our record computer.

Fix new SecurityStatuses in the CD record computer

---

Resources/Prototypes/_CD/Body/Prototypes/avali.yml

I was not made aware of this and I don't want it. Diets shouldn't be thrown around willy nilly (especially with how shit they are rn) and I don't think it particularly fits either

Remove Avali reptilian stomach

---

Resources/Prototypes/Entities/Clothing/Eyes/hud.yml

Added flash protection to sechuds.
As we discussed in discord a few weeks ago: provides additional cosmetic
options because a lot of people think sec glasses don't look very good.
**Changelog**
:cl: Aquif
- add: Sechuds now have flash protection

Add flash protection to sechud

---

Resources/Prototypes/_CD/Roles/Jobs/Security/senior_officer.yml

Senior Officers no longer get rubbers.

Remove rubbers from Senior Officer

---

Resources/Prototypes/_CD/Entities/Mobs/Species/vulpkanin.yml
Resources/Prototypes/_CD/Species/vulpkanin.yml

First round of vulp improvements.
- Changes the default tail marking.
- The sprite for when pie covers their face works now.
Basically a webedit, I'm unable at current to test these.
Improving a player species and ticking off some things in #222

Generic vulp improvements pt1

---

Content.Server/Communications/CommunicationsConsoleComponent.cs
Content.Shared/CCVar/CCVars.cs

Title.
I have seen a ton of people get their message massively cut off. It also often happens
that multiple heads want to make their own announcement at the same time. I
don't think we are that worried about people spamming the console on CD. I also
made an [upstream PR](https://github.com/space-wizards/space-station-14/pull/27145) to properly fix the message being cut off.
**Changelog**
:cl: Aquif
- tweak: Increase communication console character limit and lower the cooldown.

Increase comms console character limit and lower cooldown

---

Content.Server/RoundEnd/RoundEndSystem.cs

I added Loc.GetString to the shuttle-vote-user. This was somehow an oversight, and caused the shuttle vote user to appear as "shuttle-vote-user" for ages now
Simple bugfix
Wrote a bunch of super high level code that resulted in what you see right here.
none
**Changelog**
:cl: YuNii
- fix: Fixed the name of the shuttle vote user appearing as shuttle-vote-user.

fix shuttle vote user not showing

---

Resources/Maps/Misc/terminal.yml

Removes the rubber bullet magazine in security.
Rubber Rounds shouldn't be accessible roundstart like this. Not anymore.
Resaved the map hence such a large diff. Lots of stuff got auto-updated.

Arrivals Hotfix 1.04.1

---

Resources/Locale/en-US/_CD/preferences/loadout-groups.ftl
Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Medical/paramedic.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Wildcards/prisoner.yml
Resources/Prototypes/_CD/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/role_loadouts.yml

- **Add paramedic ETU loadout**
- **Joke Emag loadout for Prisoner**
Upstream parity
too much YAML + a lack of sanity, you may find this script helpful for generating starting gear sets (it is intended to be used with `:r !ss14loadouttool ....` in nvim)
```sh
#!/bin/sh
[ -z "$1" ] && { echo ss14loadouttool [position] [item]; exit 1; }
[ -z "$2" ] && { echo ss14loadouttool [position] [item]; exit 1; }
if [ -z "$3" ]; then
shortname=$2
else
shortname=$3
fi
echo "- type: loadout"
echo "  id: $shortname"
echo "  equipment: $shortname"
echo
echo "- type: startingGear"
echo "  id: $shortname"
echo "  equipment:"
echo "    $1: $2"
```
**Changelog**
:cl: Aquif
- add: ETU equipment is now available as a loadout for parameds.

ETU and Additional Prisoner Loadouts

---

Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Entities/Clothing/Head/helmets.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Medical/paramedic.yml

- **Mark ETU Pilot Helmet as DEBUG**
- KittenColony said this was intended to me a debug item
- **Remove ETU pilot helmet from loadouts**
- **Disable ETU harness from loadouts**
- Someone needs to fill it with the EMT belt gear before it can be used in
loadouts. In addition, I incorrectly assumed it was a harness when it was
a belt.

Fix ETU Loadout

---

Content.Shared/Nutrition/Components/HungerComponent.cs
Content.Shared/Nutrition/Components/ThirstComponent.cs

Cursed webedit 4.
Should work fine. Some custom species might have issues still.

Halve Hunger and Thirst

---

Content.Server/_CD/Records/CharacterRecordsSystem.cs

Skips loading cyborg records. I will probably add proper cyborg records at some
point. I just don't want to do it until records are in a more stable state. I
also want whatever "maintenance records" I create to apply to synth characters
as well.
Graham is not a 90 year old female moth.
We just add an if statement that skips borgs when records are loaded into the game.

Skip loading records from cyborgs.

---

Resources/Prototypes/GameRules/events.yml

Comments out sleeper agent gamerule.
Such high stress events should be left up to admins.

Removed Sleeper Agents

---

Resources/Locale/en-US/_CD/implant/overides.ftl

Change the description of mindcontrol implants.
We have said in discord that they don't control your mind. Also, mind control
is stupid.
Override the description using localization.
**Changelog**
- Not needed

Mindshield implants no longer control your mind

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs
Content.Server/_CD/Records/Consoles/CharacterRecordConsoleSystem.cs
Resources/Prototypes/Entities/Mobs/Player/admin_ghost.yml

- **Improve how the selected record is handled**
- This removes a ton of overall jank
- **Searching for records by name also searches by job**
- **Fix aghost Character Record Viewer**
QOL/Obvious Bugs
The old code did a bunch of things in stupid ways. This makes them work in less-stupid ways.
**Changelog**
:cl:
- fix: All three character record consoles should feel better to use. A few subtle issues were fixed.
- change: Searching by name in the record console also searches by job. You can just search "clown" to see the clown's records.
ADMIN:
:cl:
- fix: The aghost record console was fixed. Why did nobody tell me it was broken!
- change: Searching by name in the aghost record console can search by name, NetEntity, and Job.

Record Console Qol

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs

This should™ fix the issue where the records console would "bug out" when selecting something that required scrolling to reach.
UX improvements are good.
We check to see if the state includes new information and only repopulate if it does.
**Changelog**
Not needed

Only repopulate the records console when needed.

---

Content.Shared/Interaction/SharedInteractionSystem.cs

Fix Bag Interaction

---

Resources/Maps/Misc/terminal.yml

- Cameras.
- Headphones in the central clothing room.
- Poppy and toolbox altar in maints.
- Skirt of life in medical.
- New admin zone additions.
Cameras to make the place feel more lived in, additions to flesh things out more, admin additions for QoL.

Terminal Update 1.07

---

Resources/Locale/en-US/reagents/meta/narcotics.ftl

These names are confusing and stupid. If upstream ever changes the name of
these this PR should be reverted.
We talked about it in discord.
I just looked up a list of ss13 chems and copied a few that sounded good. If
you think they suck feel free to tell me to change it.
None
**Changelog**
:cl: Aquif
- The drug "Stimulants" has been renamed to "Hyperzine" and the drug "Space Drugs" has been renamed to "Space Mirage" in hopes of reducing confusion.

Fix stupid chem names.

---

Content.Server/StationRecords/Systems/StationRecordsSystem.cs
Content.Server/_CD/Loadouts/RenameIdComponent.cs
Content.Server/_CD/Loadouts/RenameIdSystem.cs
Content.Server/_CD/Records/CharacterRecordsSystem.cs
Resources/Locale/en-US/_CD/job/job-names.ftl
Resources/Prototypes/Loadouts/role_loadouts.yml
Resources/Prototypes/_CD/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_CD/Loadouts/Jobs/Science/titles.yml
Resources/Prototypes/_CD/Loadouts/loadout_groups.yml

Add a system for loadouts that change the title of the player's job without
changing anything else. Right now, this just includes roboticist as an
alternate scientist. It currently does not change the late join announcement
because I could not think of a way of doing it that was not very invasive to
wizden code.
It is a cosmetic change that adds to RP.
Loadouts that want to rename an ID can equip a PDA with the RenameIdComponent.
None
**Changelog**
:cl:
- Roboticist has been added as an alternate title for scientist. You can change your title by changing your PDA in the scientist loadout.

Job Title Loadouts

---

Content.Server/_CD/Loadouts/RenameIdSystem.cs

Fixes the issue where IDs would only be renamed when late joining.
Bugfix
We need to subscribe to both of these because RulePlayerJobsAssignedEvent only
fires on round start and messes up what we do in PlayerSpawnCompleteEvent.
**Changelog**
N/A

Fix titles not being applied on round start

---

Resources/Locale/en-US/tips.ftl

Moves CD's tips to the new system. There is also a few new ones because I
wanted to keep the same number of tips as upstream.

Update CD's tips to the new system.

---

Content.Shared/CCVar/CCVars.cs

Just updating the default so I don't have to do it myself.

Update Rules Config

---

Resources/Locale/en-US/_CD/guidebook/guides.ftl

title
The close master PR bot is dumb and stupid.

Fix missing localization in guidebook

---

Resources/Locale/en-US/reagents/meta/narcotics.ftl

Reverts cosmatic-drift-14/cosmatic-drift#286
I am preemptively reverting this to make merging https://github.com/space-wizards/space-station-14/pull/28989 easier.

Revert "Fix stupid chem names."

---

Resources/Prototypes/Entities/Objects/Misc/secret_documents.yml

Makes the emergency security documents into a folder.
Right now, they don't really have a use. This let's us give them a use via SOP.
Add storage component and change parent to BaseStorageItem
None
**Changelog**
:cl: Aquif
- add: The Emergency Security Orders now function as a folder.

Make HoS's orders into a folder

---

Content.Server/Shuttles/Systems/ArrivalsSystem.cs

Reverts cosmatic-drift-14/cosmatic-drift#308
It did not work.

Revert "Revert part of 'Make station components use StationPostInitEvent' "

---

Content.Server/RoundEnd/RoundEndSystem.cs
Content.Server/_CD/RoundEnd/ShuttleVoteSystem.cs
Resources/Locale/en-US/_CD/round-end/shuttle-vote.ftl
Resources/Locale/en-US/round-end/round-end-system.ftl
Resources/Prototypes/_CD/Datasets/shutle-vote-users.yml

Most of the shuttle vote code was moved to a system under our namespace. Also
add random "fun" shuttle vote users.
Namespacing is good.
Copy+Paste
While it is possible to 100% namespace this, we still would have needed to
disable the wizden shuttle vote system so I opted to just call into our system
from the wizden `RoundEndSystem`.
None
**Changelog**
N/A

Namespace shuttle vote system and add a random shuttle-vote-user

---

Resources/Prototypes/Maps/oasis.yml

I hate this map. Nairod wouldn't let me derotate it but, at the very least it is really big and probably warrants a high starting pop.

Make Oasis 55 pop

---

.vscode/settings.json
Content.Server/Maps/GameMapPrototype.CDMapPatches.cs
Content.Server/_CD/MapPatch/CDMapPatch.cs
Content.Server/_CD/MapPatch/CDMapPatchCommand.cs
Content.Server/_CD/MapPatch/MapPatchSystem.Patchfile.cs
Content.Server/_CD/MapPatch/MapPatchSystem.cs
README.md
Resources/CDMapPatches/README.md
Resources/CDMapPatches/dev_map.yml
Resources/Locale/en-US/_CD/admin/mappatches.ftl
Resources/Prototypes/Maps/debug.yml

Implements a mechanism to apply patches to maps (currently, only adding new entities) without modifying the map file itself, only a patchfile.
Maps aren't really something you can resolve conflicts in right now.
Provides a verb to add an object to the patch set, and commands to print the set, save the set, and clear the set. Intended for local use, I didn't implement a per-player patchset. Saves into the server's data directory.

Map patching system.

---

Resources/CDMapPatches/bagel.yml
Resources/CDMapPatches/core.yml
Resources/CDMapPatches/marathon.yml
Resources/CDMapPatches/meta.yml
Resources/Prototypes/Maps/bagel.yml
Resources/Prototypes/Maps/core.yml
Resources/Prototypes/Maps/marathon.yml
Resources/Prototypes/Maps/meta.yml

Adds a basic map patch that adds lost+found and a few more record
consoles to Bagel, Core, Marathon, and Meta.
Admins always forget
Map patch
**Changelog**
:cl: Aquif
- tweak:  Bagel, Core, Marathon, and Meta will have lost and found lockers automatically spawn. (credit to Moony for the map patch system)

Map patch for Bagel, Core, Marathon, and Meta

---

Content.Shared/Vehicle/SharedVehicleSystem.cs

For some reason "buckledevent" is wrong and "strappedevent" is right.

Fix Vehicles

---

Resources/Prototypes/_CD/Maps/gemini.yml

Title
Gemini's min pop is currently lower then it was when it was in-rotation upstream. In addition, we vary rarely have 45 players
online at the start of the round so Gemini will almost never be played with the old numbers.
One line change
N/A
No
**Changelog**
N/A

Lower gemini's minimum pop to 35

---

Content.Server/Paint/PaintSystem.cs

Fixes the following:
- You can only paint things that are blacklisted
- If an item was blacklisted it would show the user that the can was out of paint
- It now checks if an item can be painted *before* the doafter
Future Work:
The paint system does not exist upstream so it should be moved to our namespace at some point.
Painting is broken.
**Changelog**
:cl:
- fix: Painting no longer only works on items that cannot be painted and it will stop you from painting something that cannot be painted before the doafter bar instead of after.

Fix a few issues with painting

---

Resources/Prototypes/Entities/Mobs/Customization/Markings/human_hair.yml
Resources/Prototypes/Species/moth.yml

Moth Hair.

---

Resources/Prototypes/_CD/Entities/Clothing/OuterClothing/coats.yml

Removes named references player-side to Barotrauma in the Europan jackets
lank asked me to
name / desc changes
**Changelog**
no cl no fun

Cosmatic Drip 1.5

---

Resources/Maps/_CD/gemini.yml
Resources/Prototypes/_CD/Maps/gemini.yml

- Added vents and scrubbers to the animal pens to stop them from suffocating 
- Changed Cloning out for a Psychology office 
- Added a Psychology job slot
- Moved a strangely placed fire extinguisher in the courtroom to stop criminals from breaking out
For the fire extinguisher, it was not intended to be accessible from the jail cell (I hope). For the others- cloning is not something that is guaranteed anymore, and keeping the space there would be needlessly wasteful when we could have more dedicated RP space on a larger station. And who wants to be a zoo keeper.... when your animals _**will**_  die.
Fire Extinguisher new placement
Updated Animal Pens
Psychology Office
**Changelog**
:cl:
- add: Added Psychology Office!
- fix: Put vents and scrubbers in the animal pens. No more suffocating …

Gemini Maintenance Patch

---

Resources/Prototypes/Entities/Objects/Misc/books.yml

Title
Fixes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/334
It will link to our space law when it is complete.
YAML change
**Changelog**
None

Make space law book link to our IC policy page

---

Content.Server/_CD/RoundEnd/ShuttleVoteSystem.cs

biggest mald PR of my life (I don't really think we should continue a round where 50% of the server wants to leave)

make tied shuttle votes pass

---

Content.Shared/CCVar/CCVars.cs

Doubles the round restart time to 10 minutes as voted in the poll.
vote
webedit
yes
None
**Changelog**
:cl: Aquif
- tweak: The time at CentCom was increased to 10 minutes.

Double round restart time

---

Resources/Prototypes/Maps/cog.yml

Adds all senior roles.
Adds a prisoner role.
Adjusts the security roles to fit the rest of our maps.
Sets the pop range to 30-40 as a place holder for now.
Just to make sure everything's fairly functional for the upcoming sessions in case the vote results can't be implemented in time.
**Changelog**
(Does it require one?) Cog has been given senior roles, a prisoner role, and given a place holder pop range of 30-40.

Cog CD Prototype Changes

---

Resources/Locale/en-US/_CD/guidebook/guides.ftl
Resources/Prototypes/_CD/Guidebook/sop.yml
Resources/ServerInfo/Guidebook/_CD/sop/cargo.xml
Resources/ServerInfo/Guidebook/_CD/sop/core.xml
Resources/ServerInfo/Guidebook/_CD/sop/engi.xml
Resources/ServerInfo/Guidebook/_CD/sop/restricted.tbl
Resources/ServerInfo/Guidebook/_CD/sop/restricted.xml
Resources/ServerInfo/Guidebook/_CD/sop/sci.xml
Resources/ServerInfo/Guidebook/_CD/sop/service.xml

Updates to latest version of SOP
See discord
**Changelog**
The SOP has some additions see https://discord.com/channels/1163352113162768436/1166958602502799461/1275184452645163068 for a list of changes. The in-game guidebook has been updated to reflect this along with the google doc.

Update to latest version of SOP

---

Content.Client/_CD/Records/UI/CharacterRecordViewer.xaml.cs

Fixes https://github.com/cosmatic-drift-14/cosmatic-drift/issues/379
bugfix
The admin viewer would randomly de-select the entry because for some reason the
game repeatedly updates the BUI client side even if the server sends no new
info but ONLY for aghost UIs.

Fix admin record viewer

---

Content.Server/_CD/CryoSleep/CryoSleepSystem.cs

Title
The cryosleep rule is basically unenforceable right now due to these not existing.
**Changelog**
:cl: Aquif
ADMIN:
- add: Players entering cryosleep are now logged under the Respawn category.

Admin logs for cryosleep.

---

Resources/Locale/en-US/guidebook/guides.ftl
Resources/Prototypes/Guidebook/rules.yml
Resources/ServerInfo/Guidebook/ServerRules/CosmaticDriftRules.xml
Resources/ServerInfo/Guidebook/ServerRules/RoleplayExpectations/Rule3-8.xml

Adds rule 3.8, which covers silicon rules.
Just needed something concrete to point to, also AI coming soon:tm:
**Changelog**
Announcement level change. Will handle once merged.

Silicon Rules

---

Content.Server/_CD/Spawners/ArrivalsSpawnPointComponent.cs
Content.Server/_CD/Spawners/ArrivalsSpawnPointSystem.cs
Resources/Prototypes/_CD/Entities/Markers/Spawners/jobs.yml

oopsies.
This is not the ideal way of doing this, but it works.

Fix AI Arrivals Spawning

---

Resources/Maps/_CD/aspid.yml
Resources/Prototypes/_CD/Maps/aspid.yml

Adds a new AI core room, and well, AI core itself.
Adds the AI role.
Redoes several cameras, adds a few other.
AI, simple as that.
**Changelog**
Aspid now has AI and an AI core under engineering.

Aspid AI Update

---

Content.Server/Connection/ConnectionManager.Whitelist.cs
Content.Server/_CD/Connection/Whitelist/ConditionWhitelistSlots.cs
Resources/Locale/en-US/_CD/connection/connection-messages.ftl
Resources/Prototypes/_CD/whitelists.yml

Fairly large change to upstream code but as far as I can tell it's necessary. Also will cause more performance issues than Debug's system but I'm not certain if that'd be possible with the newer whitelist code, and the goal is just to get this ready for our next playtest.

Re-Add Whitelist Slots

---

Resources/Maps/_CD/gemini.yml
Resources/Prototypes/_CD/Maps/gemini.yml

- Adds a plethora of cameras to make playing as an AI less annoying. (Note: The names are Not Good.)
- Replaces all the doors in Science to allow Research Assistants to open them
- Patches an issue with wiring near dorms to allow the APC to actually work
- Adds a Church Bell to the Chapel
- Adds in an AI Core, Upload Console, and Lawset chips to the AI Sat
A lot of things had to be added in order to allow players to play as the new AI role, as well as a few patches to content to allow it to work properly
No.
- [X ] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X ] I have added screenshots/videos …

Gemin-AI Update

---

Content.Server/_CD/Records/CharacterRecordsSystem.cs
Content.Server/_CD/Records/SkipLoadingCharacterRecordsComponent.cs
Resources/Prototypes/Roles/Jobs/Science/borg.yml

Title
The records system does not really work for silicons.
Switched it from a blacklist of job prototypes to a component.
**Changelog**
Like borgs, the Station AI will no longer have character records.

Disable loading station records for AI.

---

Resources/Prototypes/_CD/Voice/lay_emotes.yml

Adds additional emote chat triggers for lying down.
Enables greater artistic expression for roleplayers by expanding the means through which one can make spessman horizontal.
This is technically a mald PR.
Four whole lines were added to the file to allow "falls" and minor grammatical variations to act as triggers for the emote.
N/A
**Changelog**
:cl:
- add: Emoting "falls"/"fall" now acts as a trigger for the Lay Down emote.

Add 'falls' and variations to the lay emotes.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
README.md

Adds repo documentation, mainly to explain our PR guidelines that have not been
written down at any point in time.

Add repo documentation.

---

Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/Miscellaneous/trinkets.yml

Bring your plushie to work day!
This PR adds the other (currently existing) species plushies to the loadout system, as well as the three shark plushies.
Unfortunately we don't have avali or slime (species) plushies.
Lizards can't have all the plushies :/
I saw someone talking about getting a vox plushie for their vox whenever possible and thought it would be nice if they could just have it on round start.
**Changelog**
Vox, human, arachnid, moth and diona plushies are now available in loadouts.

add more plushies to loadouts

---

Resources/Prototypes/Catalog/VendingMachines/Inventories/dinnerware.yml

The dinnerware vendor in the kitchen now has some fancy bowls. (5 in total)
I'm a chef main and I **NEED** fancy bowls for my fancy soups :)
i vended one
**Changelog**
Chefs now have access to fancy bowls for all their fancy soup needs.

fancy bowls in the dinnerware vendor

---

Resources/Prototypes/Entities/Mobs/Player/silicon.yml

AI can use the hailing channel now

---

Resources/Prototypes/_CD/Entities/Mobs/Species/rodentia.yml
Resources/Prototypes/_CD/Entities/Objects/Misc/mouth_storage.yml

Whoops.
So apparently noSpawn became obsolete in the time it took the PR to be merged.
the opps are out for the cool rat people :/

fix the noSpawn in rat people yaml

---

Resources/ServerInfo/Guidebook/_CD/sop/cargo.xml
Resources/ServerInfo/Guidebook/_CD/sop/command.xml
Resources/ServerInfo/Guidebook/_CD/sop/core.xml
Resources/ServerInfo/Guidebook/_CD/sop/restricted.xml
Resources/ServerInfo/Guidebook/_CD/sop/sci.xml
Resources/ServerInfo/Guidebook/_CD/sop/substances.tbl

Updates the in-game SOP and rearranges some inconsistent section placement between the web and guidebook versions. (File diff hates this, sue me.)
Just updates.
(I didn't use whatever Aquif set up for the tables, I just manually did it.)
Table did work:
**Changelog**
(I will do an announcement when it's merged.)

Update to the Latest Version of SOP

---

Content.Server/Voting/Managers/VoteManager.DefaultVotes.cs
Content.Server/_CD/RoundEnd/ShuttleVoteSystem.cs

this was kinda always the plan but now it's possible

Hide Round End & Map Vote Counts

---

Resources/Prototypes/Entities/Structures/Machines/Computers/computers.yml

fixes security record consoles

Fix security records consoles

---

Resources/Prototypes/Catalog/Cargo/cargo_vending.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/clothesmate.yml
Resources/Prototypes/Catalog/VendingMachines/Inventories/winterdrobe.yml
Resources/Prototypes/Entities/Clothing/OuterClothing/wintercoats.yml
Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpskirts.yml
Resources/Prototypes/Entities/Clothing/Uniforms/color_jumpsuits.yml
Resources/Prototypes/_CD/Catalog/Cargo/cargo_vending.yml
Resources/Prototypes/_CD/Catalog/VendingMachines/Inventories/quickthreads.yml
Resources/Prototypes/_CD/Entities/Clothing/Uniforms/color_jumpskirts.yml
Resources/Prototypes/_CD/Entities/Clothing/Uniforms/color_jumpsuits.yml

-Added 11 types of colored winter coats to the winterdrobe
-Added 16 dresses to the quickthreads
-Recolored the purple jumpsuit and skirt
-Made the old version into a new jumpsuit and skirt(lilac)
-Added Lilac, Maroon, Brown and Light Brown jumpsuits and skirts into the clothesmate
-Recolored the worn sprite of the black winter coat to be slightly lighter
More drip. Restocks more expensive, but that's about it.
**Changelog**
-Add:Added 11 types of colored winter coats to the winterdrobe
-Add:Added 16 dresses to the quickthreads
-Add:Added Dark Purple, Maroon, Brown and Light Brown jumpsuits and skirts into the clothesmate

Colored Drip 1 - Coats, Dresses, Jumpsuits and Skirts

---

Content.Server/Ninja/Systems/SpiderChargeSystem.cs
Content.Shared/Mind/SharedMindSystem.cs
Content.Shared/Storage/EntitySystems/SecretStashSystem.cs

Entirely hotfixes but worth doing regardless.

Merge Stable 22/10/24

---

Resources/Prototypes/Hydroponics/seeds.yml

Revert #7 at the request of @Skarletto.

Revert #7 "botany gaming but LONGER"

---

Resources/Prototypes/GameRules/events.yml

I halved most of them. There are a lot so I'm not sure exactly what this'll do but, oh well.

Nerf vent critter events

---

Resources/Prototypes/Loadouts/Miscellaneous/trinkets.yml

title
https://github.com/cosmatic-drift-14/cosmatic-drift/issues/454

remove role playtime requirements from towels

---

Content.Server/_CD/Engraving/EngraveableComponent.cs
Content.Server/_CD/Engraving/EngraveableSystem.cs

fix dogtags

---

.github/CODEOWNERS

Adds a CODEOWNERS file. I have been currently using github notifications to keep track of what PRs need review, but this has become unsustainable due to the recent influx of PRs CD has been getting. This allows PRs that need review to show up in a nice list for me. I have intentionally excluded myself from PRs that exclusively contain mapping/art changes.
@Nairodian @LankLTE do ether of you want to be added to this list while I am working on it? If so, what files do you care about? You can also push to this branch directly.

Add CD CODEOWNERS

---

Resources/Prototypes/Species/human.yml

Let there be cats.
You can ask the admins for cat features already, so this makes no difference :)
Admin workload reduced! Yippee!!
allows humans to have tails in general, which they couldnt natively have before
**Changelog**
The cat part markings for humans have been enabled. Humans can now willingly become cat people. Rejoice.

enable the dreaded cat markings for humans

---

Resources/Prototypes/_CD/Body/Prototypes/vulpkanin.yml

you guys have been living like this the whole time??
before:
after:
it's the other way around

unflip vulpkanin arms

---

Resources/Prototypes/Guidebook/rules.yml
Resources/Prototypes/Guidebook/security.yml
Resources/Prototypes/_CD/Guidebook/sop.yml
Resources/ServerInfo/Guidebook/ServerRules/SpaceLaw/CDSpaceLaw.xml

Title, I have been holding off on this because space law is "just a week away". However, new security players are constantly confused by this so I think it is time we actually do something about it.

Remove references to modern wizden space law

---

Content.Server/StationEvents/Events/GreytideVirusRule.cs
Resources/Locale/en-US/_CD/station/events.ftl
Resources/Prototypes/GameRules/events.yml

The announcement now fits better IC & it's locked to severity 1.

Change the greytide virus to be more fitting.

---

Content.Server/_CD/Records/RecordsSerialization.cs

This function was literally not being used. In addition, it is entirely useless.
Removed a function in `RecordsSerialization` that was unused.

Remove useless function

---

Resources/Prototypes/Entities/Objects/Specific/Medical/handheld_crew_monitor.yml
Resources/Prototypes/Objectives/objectiveGroups.yml
Resources/Prototypes/Objectives/stealTargetGroups.yml
Resources/Prototypes/Objectives/traitor.yml

Apparently I was wrong and we use traitor objectives for some things.

Remove the crew monitor as an antag target

---

Resources/Prototypes/Maps/Pools/default.yml

Done at the request of Nairod.

Derotate Amber Temporarily

---

Resources/Prototypes/Entities/Structures/Power/smes.yml

Our SMES were already buffed and thus identical to the advanced SMES. This buffs the advanced one to compensate.

Buff Advanced SMES

---

Content.Client/UserInterface/Systems/Bwoink/AHelpUIController.cs

Nairod's slow and couldn't write up something so we need to just remove it for now.

Temporarily remove the ahelp intro message

---

Resources/Locale/en-US/_CD/seeds/seeds.ftl

Localisation addition
**Changelog**
no 🆑 no fun

Mindleaf locale fix

---

Resources/Maps/_CD/Shuttles/mining.yml
Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
Resources/Prototypes/Entities/Stations/base.yml
Resources/Prototypes/_CD/Entities/Objects/Devices/Circuitboards/computer.yml
Resources/Prototypes/_CD/Entities/Structures/Machines/Computers/computers.yml
Resources/Prototypes/_CD/Entities/Structures/Machines/Computers/tabletopcomputer.yml
Resources/migration.yml

https://github.com/cosmatic-drift-14/cosmatic-drift/pull/427/ revival
see original PR for context
**Changelog** (MilonPL and Mangohydra)
The reclaimer has returned (but broken).
Salvage shuttle boards and computers exist again.
Qm lockers come with 1 spare salvage shuttle console board.

Re-adding the Salvage Shuttle, take 2

---

Resources/Prototypes/Species/vox.yml

Little reason to have this restricted. Will need an announcement saying vox colors will be fucked.

Unrestrict Vox Colors

---

Resources/Prototypes/Maps/Pools/default.yml

They're new and need CD stuff.

Temporarily derotate Elkridge & Plasma

---

Resources/Locale/en-US/_CD/traits/traits.ftl
Resources/Prototypes/_CD/Traits/speech.yml

Russian Accent Trait

---

Resources/CDMapPatches/elkridge.yml
Resources/CDMapPatches/loop.yml
Resources/CDMapPatches/plasma.yml
Resources/Prototypes/Maps/Pools/default.yml
Resources/Prototypes/Maps/elkridge.yml
Resources/Prototypes/Maps/loop.yml
Resources/Prototypes/Maps/plasma.yml

Changes Elkridge, Loop, and Plasma station.
- Adjusts the player maximums and minimums.
- Adds CD roles.
- Adjusts Upstream role counts.
- Adds map patches for CD entities.
- Rerotates them.
**Changelog**
Elkridge, Loop, and Plasma station have been updated to match CD and re-rotated.

Triple Patch Threat

---

Resources/Prototypes/Traits/speech.yml

I see no reason for this to cost anything

Make Accentless Trait Free

---

Content.Shared/Doors/Systems/SharedAirlockSystem.cs

Someone in vc told me this was a bug in CD too
https://github.com/user-attachments/assets/93cfbe15-2989-4913-9188-fda34f486140
**Changelog**
Fixed crowbars not being able to close unpowered doors.

Fix crowbars not being able to close unpowered doors

---

Resources/Prototypes/GameRules/roundstart.yml
Resources/Prototypes/GameRules/unknown_shuttles.yml

Remove Hostile Shuttles

---

.github/workflows/cd-build-upload-artifact.yml

This should fix the binary artifacts.

Dotnet version bump for binary artifacts

---

Resources/Prototypes/_CD/Reactions/narcotics.yml

Adds a reaction for Breakout to be made without first drying the leaves
**Changelog**
Breakout can now be made by heating Mindleaf sap to 393K

Breakout Creation

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Update the PR template and CONTRIBUTING to address the most common reasons PR's get rejected or changes requested.

Template changes

---

Resources/Maps/Misc/terminal.yml

This fix doesn't seem like it *should* work, but to my (limited) testing it did. The map at least loaded and arrivals cycled fine, so.

Fix Arrivals

---

Resources/ServerInfo/Guidebook/_CD/sop/core.xml
Resources/ServerInfo/Guidebook/_CD/sop/med.xml
Resources/ServerInfo/Guidebook/_CD/sop/sci.xml
Resources/ServerInfo/Guidebook/_CD/sop/security.xml

Updates the SOP to the newest version, including Amber, Bronze, and Omega alerts, general Alert procedure, science Silicon Malfunctions procedure, and medical Treatment procedure.
For #571
**Changelog**
SOP has been updated to include Amber, Bronze, and Omega alert procedures, as well as an entry for medical treatments and malfunctioning silicons.
[I'll probably include a lesser board announcement with this.]

SOP Alert Levels Update

---

Resources/Locale/en-US/_CD/ghost/roles/ghost-role-component.ftl
Resources/Prototypes/_CD/Entities/Mobs/NPCs/pets.yml

Makes Pebble a ghost role, shouldn't be an issue.
**Changelog**
Still not mapped so probably not.

Pebble Ghost Role

---

Resources/Prototypes/Entities/Markers/Spawners/Random/anomaly.yml

I think it being 1/3 is probably unintentional, I swear we had it lower originally, but imho this should be rare so 1/20 is fine.

Make anomalous infections less common

---

Resources/Prototypes/GameRules/events.yml

Take a shot every time I said "pending rework" in this PR

Disable paradox pending rework

---

Resources/Prototypes/_CD/Loadouts/role_loadouts.yml

Resolves #456.
Glasses were added to all CD roles except for... most of them. PI and Senior Officer excluded because all of Security is due to having sec glasses. Senior Engineer excluded because all of Engineering is due to... not 100% sure why. Prisoner excluded because they are excluded from just about all loadouts.
**Changelog**
Added glasses to Senior Researcher and Senior Physician loadouts.

Added glasses to CD role loadouts.

---

Resources/Prototypes/_CD/Catalog/Cargo/cargo_vending.yml

Fixes the arbitrage test failure introduced by https://github.com/cosmatic-drift-14/cosmatic-drift/pull/588

Fix arbitrage test

---

Resources/Prototypes/Guidebook/rules.yml
Resources/ServerInfo/Guidebook/ServerRules/CosmaticDriftRules.xml
Resources/ServerInfo/Guidebook/ServerRules/RoleplayExpectations/Rule3-0.xml
Resources/ServerInfo/Guidebook/ServerRules/RoleplayExpectations/Rule3-9.xml

Adds a rule to ensure characters are reasonable and don't venture too far out of universe.
**Changelog**
I'll make an announcement.

Mary Sue Rule

---

Content.Server/_CD/Loadouts/RenameIdComponent.cs
Content.Server/_CD/Loadouts/RenameIdSystem.cs
Resources/Prototypes/Entities/Objects/Devices/pda.yml
Resources/Prototypes/_CD/Entities/Objects/Devices/pda.yml

Icons for alternate titles.
**Changelog**
All Intern and Roboticist alternate titles now have icons.

Alt title icons

---

Content.Client/Humanoid/HumanoidAppearanceSystem.cs
Content.Shared/Humanoid/Markings/MarkingPrototype.cs
Tools/markings/markings/prototypes.go

Adds support for unshaded markings!!
**Changelog**
Adds support for unshaded markings. You'll see the effect of this in future PRs.

Unshaded Markings

---

Resources/Prototypes/Maps/Pools/default.yml

Derotate Exo

---

Resources/Maps/_CD/aspid.yml

A very small update adjusting a couple pipes in atmos to make it more sane, also adds security and AI turrets.
**Changelog**
Probably small enough not to warrant one, but just in case; Atmos got a very small update to atmos using pipe layers to make it a bit more sane. The AI core and armory now have turrets installed.

Aspid Minor Atmos Update

---

.github/PULL_REQUEST_TEMPLATE.md

This PR mostly just slightly reformats the "Requirements" part to be consistent and a bit easier to read (with **bolding**)
I also made some typo fixes in the comments
(this PR uses the updated template. with the usual trimming I do of parts that aren't relevant)

Minor formatting changes for the pull request template

---

Resources/Locale/en-US/_CD/job/editor-warnings.ftl

Typos. "Service" should be a proper noun

Typofixes the editor warning in the job panel

---

Resources/Prototypes/Actions/types.yml

This missing line caused it to not work.

Fix tail wagging.

---

Resources/Locale/en-US/ghost/roles/ghost-role-component.ftl

100% untested. Fixed broken locale.

Fix closet skeleton rules introduced in #253

---

Resources/Prototypes/Loadouts/loadout_groups.yml
Resources/Prototypes/_CD/Loadouts/Miscellaneous/trinkets.yml

Added spesos as a trinket in 10 and 100 speso stacks.
**Changelog**
Add spesos as a trinket option.

Add Spesos as a Trinket

---

Resources/Prototypes/Entities/Objects/Devices/pda.yml

Fixes #707
100% untested. Should be fine.
**Changelog**

Give QM Nanochat

---

Content.Server.Database/Migrations/Postgres/20250609134446_CDAllergies.cs

Fix the postgres migration for #649. 
Copy the sqlite migration to the postgres migration. It seemed to work
correctly on my test db but as always make sure to take a backup before you
apply DB migrations
I would like to take this moment to rant about EF core. The migration generator
shits itself if you look at it in the wrong way and is very not deterministic.
Git restoring the files then running the migration generator again can produce
different results. On top of that, EF core is a massive pain to debug because
of all the ""Nice abstractions"" or whatever and the documentation is
gradle-esque documentation theater.
Fixes: #725

Fix allergies migration

---

Content.Server/_CD/CartridgeLoader/Cartridges/NanoChatCartridgeSystem.cs

- Fixed notifications not being delivered if the chat was the currently selected chat. The chat will still not be marked
as unread since there is no way to mark the chat as read if the user only has one other person in their chat list.
- Made notifications ignore whether or not the chat is unread. I think the ability to spam people with notifications is
good for RP. The restriction additionally prevents people from sending a "did you see this" text a few minutes
later.
Fixes: https://github.com/cosmatic-drift-14/cosmatic-drift/issues/655
**Changelog**
Nanochat notifications are now delivered properly.

Fix Nanochat notifications

---

Content.Client/Inventory/ClientInventorySystem.cs

I don't know why this works or if it's a good idea, but here it is.

Readd OnPlayerAttached.

---

Resources/Prototypes/Entities/Structures/Dispensers/base_structuredispensers.yml
Resources/Prototypes/Entities/Structures/Dispensers/booze.yml
Resources/Prototypes/Entities/Structures/Dispensers/soda.yml

The force pushed caused some issues, this should fix it.

Fix Accidental Reverts to master
